/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDICTIONARY_H
#define _MOCKDICTIONARY_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "Dictionary.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockDictionary_Init(void);
void MockDictionary_Destroy(void);
void MockDictionary_Verify(void);


typedef int(*cmock_Dictionary_func_ptr1)(void* entry_one, void* entry_two);


#define dictionary_constructor_Ignore() TEST_FAIL_MESSAGE("dictionary_constructor requires _IgnoreAndReturn");
#define dictionary_constructor_IgnoreAndReturn(cmock_retval) dictionary_constructor_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dictionary_constructor_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, struct Dictionary cmock_to_return);
#define dictionary_constructor_StopIgnore() dictionary_constructor_CMockStopIgnore()
void dictionary_constructor_CMockStopIgnore(void);
#define dictionary_constructor_Expect(compare) TEST_FAIL_MESSAGE("dictionary_constructor requires _ExpectAndReturn");
#define dictionary_constructor_ExpectAndReturn(compare, cmock_retval) dictionary_constructor_CMockExpectAndReturn(__LINE__, compare, cmock_retval)
void dictionary_constructor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cmock_Dictionary_func_ptr1 compare, struct Dictionary cmock_to_return);
typedef struct Dictionary (* CMOCK_dictionary_constructor_CALLBACK)(cmock_Dictionary_func_ptr1 compare, int cmock_num_calls);
void dictionary_constructor_AddCallback(CMOCK_dictionary_constructor_CALLBACK Callback);
void dictionary_constructor_Stub(CMOCK_dictionary_constructor_CALLBACK Callback);
#define dictionary_constructor_StubWithCallback dictionary_constructor_Stub
#define dictionary_destructor_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dictionary_destructor requires _Ignore (not AndReturn)");
#define dictionary_destructor_Ignore() dictionary_destructor_CMockIgnore()
void dictionary_destructor_CMockIgnore(void);
#define dictionary_destructor_StopIgnore() dictionary_destructor_CMockStopIgnore()
void dictionary_destructor_CMockStopIgnore(void);
#define dictionary_destructor_ExpectAndReturn(dictionary, cmock_retval) TEST_FAIL_MESSAGE("dictionary_destructor requires _Expect (not AndReturn)");
#define dictionary_destructor_Expect(dictionary) dictionary_destructor_CMockExpect(__LINE__, dictionary)
void dictionary_destructor_CMockExpect(UNITY_LINE_TYPE cmock_line, struct Dictionary* dictionary);
typedef void (* CMOCK_dictionary_destructor_CALLBACK)(struct Dictionary* dictionary, int cmock_num_calls);
void dictionary_destructor_AddCallback(CMOCK_dictionary_destructor_CALLBACK Callback);
void dictionary_destructor_Stub(CMOCK_dictionary_destructor_CALLBACK Callback);
#define dictionary_destructor_StubWithCallback dictionary_destructor_Stub
#define compare_string_keys_Ignore() TEST_FAIL_MESSAGE("compare_string_keys requires _IgnoreAndReturn");
#define compare_string_keys_IgnoreAndReturn(cmock_retval) compare_string_keys_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void compare_string_keys_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define compare_string_keys_StopIgnore() compare_string_keys_CMockStopIgnore()
void compare_string_keys_CMockStopIgnore(void);
#define compare_string_keys_Expect(entry_one, entry_two) TEST_FAIL_MESSAGE("compare_string_keys requires _ExpectAndReturn");
#define compare_string_keys_ExpectAndReturn(entry_one, entry_two, cmock_retval) compare_string_keys_CMockExpectAndReturn(__LINE__, entry_one, entry_two, cmock_retval)
void compare_string_keys_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* entry_one, void* entry_two, int cmock_to_return);
typedef int (* CMOCK_compare_string_keys_CALLBACK)(void* entry_one, void* entry_two, int cmock_num_calls);
void compare_string_keys_AddCallback(CMOCK_compare_string_keys_CALLBACK Callback);
void compare_string_keys_Stub(CMOCK_compare_string_keys_CALLBACK Callback);
#define compare_string_keys_StubWithCallback compare_string_keys_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
