/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfifo_queue.h"

static const char* CMockString_fifo_queue_init = "fifo_queue_init";
static const char* CMockString_pop_first = "pop_first";
static const char* CMockString_push_last = "push_last";
static const char* CMockString_queue = "queue";
static const char* CMockString_task = "task";

typedef struct _CMOCK_fifo_queue_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  fifo_queue_t* Expected_queue;

} CMOCK_fifo_queue_init_CALL_INSTANCE;

typedef struct _CMOCK_push_last_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  fifo_queue_t* Expected_queue;
  struct ClientTask* Expected_task;

} CMOCK_push_last_CALL_INSTANCE;

typedef struct _CMOCK_pop_first_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  fifo_queue_t* Expected_queue;
  struct ClientTask** Expected_task;

} CMOCK_pop_first_CALL_INSTANCE;

static struct Mockfifo_queueInstance
{
  char fifo_queue_init_IgnoreBool;
  int fifo_queue_init_FinalReturn;
  char fifo_queue_init_CallbackBool;
  CMOCK_fifo_queue_init_CALLBACK fifo_queue_init_CallbackFunctionPointer;
  int fifo_queue_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE fifo_queue_init_CallInstance;
  char push_last_IgnoreBool;
  int push_last_FinalReturn;
  char push_last_CallbackBool;
  CMOCK_push_last_CALLBACK push_last_CallbackFunctionPointer;
  int push_last_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE push_last_CallInstance;
  char pop_first_IgnoreBool;
  int pop_first_FinalReturn;
  char pop_first_CallbackBool;
  CMOCK_pop_first_CALLBACK pop_first_CallbackFunctionPointer;
  int pop_first_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pop_first_CallInstance;
} Mock;


void Mockfifo_queue_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.fifo_queue_init_CallInstance;
  if (Mock.fifo_queue_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fifo_queue_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.fifo_queue_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.push_last_CallInstance;
  if (Mock.push_last_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_push_last);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.push_last_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.pop_first_CallInstance;
  if (Mock.pop_first_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_pop_first);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.pop_first_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockfifo_queue_Init(void)
{
  Mockfifo_queue_Destroy();
}

void Mockfifo_queue_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int fifo_queue_init(fifo_queue_t* queue)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fifo_queue_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fifo_queue_init);
  cmock_call_instance = (CMOCK_fifo_queue_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fifo_queue_init_CallInstance);
  Mock.fifo_queue_init_CallInstance = CMock_Guts_MemNext(Mock.fifo_queue_init_CallInstance);
  if (Mock.fifo_queue_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.fifo_queue_init_FinalReturn;
    Mock.fifo_queue_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.fifo_queue_init_CallbackBool &&
      Mock.fifo_queue_init_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.fifo_queue_init_CallbackFunctionPointer(queue, Mock.fifo_queue_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_fifo_queue_init,CMockString_queue);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_queue, queue, sizeof(fifo_queue_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.fifo_queue_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_fifo_queue_init);
    cmock_call_instance->ReturnVal = Mock.fifo_queue_init_CallbackFunctionPointer(queue, Mock.fifo_queue_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fifo_queue_init(CMOCK_fifo_queue_init_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue);
void CMockExpectParameters_fifo_queue_init(CMOCK_fifo_queue_init_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue)
{
  cmock_call_instance->Expected_queue = queue;
}

void fifo_queue_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fifo_queue_init_CALL_INSTANCE));
  CMOCK_fifo_queue_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_fifo_queue_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fifo_queue_init_CallInstance = CMock_Guts_MemChain(Mock.fifo_queue_init_CallInstance, cmock_guts_index);
  Mock.fifo_queue_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.fifo_queue_init_IgnoreBool = (char)1;
}

void fifo_queue_init_CMockStopIgnore(void)
{
  if(Mock.fifo_queue_init_IgnoreBool)
    Mock.fifo_queue_init_CallInstance = CMock_Guts_MemNext(Mock.fifo_queue_init_CallInstance);
  Mock.fifo_queue_init_IgnoreBool = (char)0;
}

void fifo_queue_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fifo_queue_init_CALL_INSTANCE));
  CMOCK_fifo_queue_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_fifo_queue_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fifo_queue_init_CallInstance = CMock_Guts_MemChain(Mock.fifo_queue_init_CallInstance, cmock_guts_index);
  Mock.fifo_queue_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_fifo_queue_init(cmock_call_instance, queue);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void fifo_queue_init_AddCallback(CMOCK_fifo_queue_init_CALLBACK Callback)
{
  Mock.fifo_queue_init_IgnoreBool = (char)0;
  Mock.fifo_queue_init_CallbackBool = (char)1;
  Mock.fifo_queue_init_CallbackFunctionPointer = Callback;
}

void fifo_queue_init_Stub(CMOCK_fifo_queue_init_CALLBACK Callback)
{
  Mock.fifo_queue_init_IgnoreBool = (char)0;
  Mock.fifo_queue_init_CallbackBool = (char)0;
  Mock.fifo_queue_init_CallbackFunctionPointer = Callback;
}

int push_last(fifo_queue_t* queue, struct ClientTask* task)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_push_last_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_push_last);
  cmock_call_instance = (CMOCK_push_last_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.push_last_CallInstance);
  Mock.push_last_CallInstance = CMock_Guts_MemNext(Mock.push_last_CallInstance);
  if (Mock.push_last_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.push_last_FinalReturn;
    Mock.push_last_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.push_last_CallbackBool &&
      Mock.push_last_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.push_last_CallbackFunctionPointer(queue, task, Mock.push_last_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_push_last,CMockString_queue);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_queue, queue, sizeof(fifo_queue_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_push_last,CMockString_task);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_task, task, sizeof(struct ClientTask), cmock_line, CMockStringMismatch);
  }
  if (Mock.push_last_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_push_last);
    cmock_call_instance->ReturnVal = Mock.push_last_CallbackFunctionPointer(queue, task, Mock.push_last_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_push_last(CMOCK_push_last_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue, struct ClientTask* task);
void CMockExpectParameters_push_last(CMOCK_push_last_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue, struct ClientTask* task)
{
  cmock_call_instance->Expected_queue = queue;
  cmock_call_instance->Expected_task = task;
}

void push_last_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_push_last_CALL_INSTANCE));
  CMOCK_push_last_CALL_INSTANCE* cmock_call_instance = (CMOCK_push_last_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.push_last_CallInstance = CMock_Guts_MemChain(Mock.push_last_CallInstance, cmock_guts_index);
  Mock.push_last_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.push_last_IgnoreBool = (char)1;
}

void push_last_CMockStopIgnore(void)
{
  if(Mock.push_last_IgnoreBool)
    Mock.push_last_CallInstance = CMock_Guts_MemNext(Mock.push_last_CallInstance);
  Mock.push_last_IgnoreBool = (char)0;
}

void push_last_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, struct ClientTask* task, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_push_last_CALL_INSTANCE));
  CMOCK_push_last_CALL_INSTANCE* cmock_call_instance = (CMOCK_push_last_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.push_last_CallInstance = CMock_Guts_MemChain(Mock.push_last_CallInstance, cmock_guts_index);
  Mock.push_last_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_push_last(cmock_call_instance, queue, task);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void push_last_AddCallback(CMOCK_push_last_CALLBACK Callback)
{
  Mock.push_last_IgnoreBool = (char)0;
  Mock.push_last_CallbackBool = (char)1;
  Mock.push_last_CallbackFunctionPointer = Callback;
}

void push_last_Stub(CMOCK_push_last_CALLBACK Callback)
{
  Mock.push_last_IgnoreBool = (char)0;
  Mock.push_last_CallbackBool = (char)0;
  Mock.push_last_CallbackFunctionPointer = Callback;
}

int pop_first(fifo_queue_t* queue, struct ClientTask** task)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pop_first_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pop_first);
  cmock_call_instance = (CMOCK_pop_first_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pop_first_CallInstance);
  Mock.pop_first_CallInstance = CMock_Guts_MemNext(Mock.pop_first_CallInstance);
  if (Mock.pop_first_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.pop_first_FinalReturn;
    Mock.pop_first_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.pop_first_CallbackBool &&
      Mock.pop_first_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.pop_first_CallbackFunctionPointer(queue, task, Mock.pop_first_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_pop_first,CMockString_queue);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_queue, queue, sizeof(fifo_queue_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_pop_first,CMockString_task);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_task, task, cmock_line, CMockStringMismatch);
  }
  if (Mock.pop_first_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_pop_first);
    cmock_call_instance->ReturnVal = Mock.pop_first_CallbackFunctionPointer(queue, task, Mock.pop_first_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pop_first(CMOCK_pop_first_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue, struct ClientTask** task);
void CMockExpectParameters_pop_first(CMOCK_pop_first_CALL_INSTANCE* cmock_call_instance, fifo_queue_t* queue, struct ClientTask** task)
{
  cmock_call_instance->Expected_queue = queue;
  cmock_call_instance->Expected_task = task;
}

void pop_first_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pop_first_CALL_INSTANCE));
  CMOCK_pop_first_CALL_INSTANCE* cmock_call_instance = (CMOCK_pop_first_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pop_first_CallInstance = CMock_Guts_MemChain(Mock.pop_first_CallInstance, cmock_guts_index);
  Mock.pop_first_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pop_first_IgnoreBool = (char)1;
}

void pop_first_CMockStopIgnore(void)
{
  if(Mock.pop_first_IgnoreBool)
    Mock.pop_first_CallInstance = CMock_Guts_MemNext(Mock.pop_first_CallInstance);
  Mock.pop_first_IgnoreBool = (char)0;
}

void pop_first_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, struct ClientTask** task, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pop_first_CALL_INSTANCE));
  CMOCK_pop_first_CALL_INSTANCE* cmock_call_instance = (CMOCK_pop_first_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pop_first_CallInstance = CMock_Guts_MemChain(Mock.pop_first_CallInstance, cmock_guts_index);
  Mock.pop_first_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pop_first(cmock_call_instance, queue, task);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pop_first_AddCallback(CMOCK_pop_first_CALLBACK Callback)
{
  Mock.pop_first_IgnoreBool = (char)0;
  Mock.pop_first_CallbackBool = (char)1;
  Mock.pop_first_CallbackFunctionPointer = Callback;
}

void pop_first_Stub(CMOCK_pop_first_CALLBACK Callback)
{
  Mock.pop_first_IgnoreBool = (char)0;
  Mock.pop_first_CallbackBool = (char)0;
  Mock.pop_first_CallbackFunctionPointer = Callback;
}

