/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockDictionary.h"

static const char* CMockString_compare = "compare";
static const char* CMockString_compare_string_keys = "compare_string_keys";
static const char* CMockString_dictionary = "dictionary";
static const char* CMockString_dictionary_constructor = "dictionary_constructor";
static const char* CMockString_dictionary_destructor = "dictionary_destructor";
static const char* CMockString_entry_one = "entry_one";
static const char* CMockString_entry_two = "entry_two";

typedef struct _CMOCK_dictionary_constructor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct Dictionary ReturnVal;
  cmock_Dictionary_func_ptr1 Expected_compare;

} CMOCK_dictionary_constructor_CALL_INSTANCE;

typedef struct _CMOCK_dictionary_destructor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct Dictionary* Expected_dictionary;

} CMOCK_dictionary_destructor_CALL_INSTANCE;

typedef struct _CMOCK_compare_string_keys_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  void* Expected_entry_one;
  void* Expected_entry_two;

} CMOCK_compare_string_keys_CALL_INSTANCE;

static struct MockDictionaryInstance
{
  char dictionary_constructor_IgnoreBool;
  struct Dictionary dictionary_constructor_FinalReturn;
  char dictionary_constructor_CallbackBool;
  CMOCK_dictionary_constructor_CALLBACK dictionary_constructor_CallbackFunctionPointer;
  int dictionary_constructor_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dictionary_constructor_CallInstance;
  char dictionary_destructor_IgnoreBool;
  char dictionary_destructor_CallbackBool;
  CMOCK_dictionary_destructor_CALLBACK dictionary_destructor_CallbackFunctionPointer;
  int dictionary_destructor_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dictionary_destructor_CallInstance;
  char compare_string_keys_IgnoreBool;
  int compare_string_keys_FinalReturn;
  char compare_string_keys_CallbackBool;
  CMOCK_compare_string_keys_CALLBACK compare_string_keys_CallbackFunctionPointer;
  int compare_string_keys_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE compare_string_keys_CallInstance;
} Mock;


void MockDictionary_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.dictionary_constructor_CallInstance;
  if (Mock.dictionary_constructor_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dictionary_constructor);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dictionary_constructor_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dictionary_destructor_CallInstance;
  if (Mock.dictionary_destructor_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dictionary_destructor);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dictionary_destructor_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.compare_string_keys_CallInstance;
  if (Mock.compare_string_keys_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_compare_string_keys);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.compare_string_keys_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void MockDictionary_Init(void)
{
  MockDictionary_Destroy();
}

void MockDictionary_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

struct Dictionary dictionary_constructor(cmock_Dictionary_func_ptr1 compare)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dictionary_constructor_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dictionary_constructor);
  cmock_call_instance = (CMOCK_dictionary_constructor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dictionary_constructor_CallInstance);
  Mock.dictionary_constructor_CallInstance = CMock_Guts_MemNext(Mock.dictionary_constructor_CallInstance);
  if (Mock.dictionary_constructor_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dictionary_constructor_FinalReturn;
    memcpy((void*)(&Mock.dictionary_constructor_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(struct Dictionary[sizeof(cmock_call_instance->ReturnVal) == sizeof(struct Dictionary) ? 1 : -1])); /* add struct Dictionary to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dictionary_constructor_CallbackBool &&
      Mock.dictionary_constructor_CallbackFunctionPointer != NULL)
  {
    struct Dictionary cmock_cb_ret = Mock.dictionary_constructor_CallbackFunctionPointer(compare, Mock.dictionary_constructor_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dictionary_constructor,CMockString_compare);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_compare, compare, cmock_line, CMockStringMismatch);
  }
  if (Mock.dictionary_constructor_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_dictionary_constructor);
    cmock_call_instance->ReturnVal = Mock.dictionary_constructor_CallbackFunctionPointer(compare, Mock.dictionary_constructor_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_dictionary_constructor(CMOCK_dictionary_constructor_CALL_INSTANCE* cmock_call_instance, cmock_Dictionary_func_ptr1 compare);
void CMockExpectParameters_dictionary_constructor(CMOCK_dictionary_constructor_CALL_INSTANCE* cmock_call_instance, cmock_Dictionary_func_ptr1 compare)
{
  memcpy((void*)(&cmock_call_instance->Expected_compare), (const void*)(&compare),
         sizeof(cmock_Dictionary_func_ptr1[sizeof(compare) == sizeof(cmock_Dictionary_func_ptr1) ? 1 : -1])); /* add cmock_Dictionary_func_ptr1 to :treat_as_array if this causes an error */
}

void dictionary_constructor_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, struct Dictionary cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dictionary_constructor_CALL_INSTANCE));
  CMOCK_dictionary_constructor_CALL_INSTANCE* cmock_call_instance = (CMOCK_dictionary_constructor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dictionary_constructor_CallInstance = CMock_Guts_MemChain(Mock.dictionary_constructor_CallInstance, cmock_guts_index);
  Mock.dictionary_constructor_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dictionary_constructor_IgnoreBool = (char)1;
}

void dictionary_constructor_CMockStopIgnore(void)
{
  if(Mock.dictionary_constructor_IgnoreBool)
    Mock.dictionary_constructor_CallInstance = CMock_Guts_MemNext(Mock.dictionary_constructor_CallInstance);
  Mock.dictionary_constructor_IgnoreBool = (char)0;
}

void dictionary_constructor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cmock_Dictionary_func_ptr1 compare, struct Dictionary cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dictionary_constructor_CALL_INSTANCE));
  CMOCK_dictionary_constructor_CALL_INSTANCE* cmock_call_instance = (CMOCK_dictionary_constructor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dictionary_constructor_CallInstance = CMock_Guts_MemChain(Mock.dictionary_constructor_CallInstance, cmock_guts_index);
  Mock.dictionary_constructor_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dictionary_constructor(cmock_call_instance, compare);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(struct Dictionary[sizeof(cmock_to_return) == sizeof(struct Dictionary) ? 1 : -1])); /* add struct Dictionary to :treat_as_array if this causes an error */
}

void dictionary_constructor_AddCallback(CMOCK_dictionary_constructor_CALLBACK Callback)
{
  Mock.dictionary_constructor_IgnoreBool = (char)0;
  Mock.dictionary_constructor_CallbackBool = (char)1;
  Mock.dictionary_constructor_CallbackFunctionPointer = Callback;
}

void dictionary_constructor_Stub(CMOCK_dictionary_constructor_CALLBACK Callback)
{
  Mock.dictionary_constructor_IgnoreBool = (char)0;
  Mock.dictionary_constructor_CallbackBool = (char)0;
  Mock.dictionary_constructor_CallbackFunctionPointer = Callback;
}

void dictionary_destructor(struct Dictionary* dictionary)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dictionary_destructor_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dictionary_destructor);
  cmock_call_instance = (CMOCK_dictionary_destructor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dictionary_destructor_CallInstance);
  Mock.dictionary_destructor_CallInstance = CMock_Guts_MemNext(Mock.dictionary_destructor_CallInstance);
  if (Mock.dictionary_destructor_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dictionary_destructor_CallbackBool &&
      Mock.dictionary_destructor_CallbackFunctionPointer != NULL)
  {
    Mock.dictionary_destructor_CallbackFunctionPointer(dictionary, Mock.dictionary_destructor_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dictionary_destructor,CMockString_dictionary);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_dictionary, dictionary, sizeof(struct Dictionary), cmock_line, CMockStringMismatch);
  }
  if (Mock.dictionary_destructor_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_dictionary_destructor);
    Mock.dictionary_destructor_CallbackFunctionPointer(dictionary, Mock.dictionary_destructor_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dictionary_destructor(CMOCK_dictionary_destructor_CALL_INSTANCE* cmock_call_instance, struct Dictionary* dictionary);
void CMockExpectParameters_dictionary_destructor(CMOCK_dictionary_destructor_CALL_INSTANCE* cmock_call_instance, struct Dictionary* dictionary)
{
  cmock_call_instance->Expected_dictionary = dictionary;
}

void dictionary_destructor_CMockIgnore(void)
{
  Mock.dictionary_destructor_IgnoreBool = (char)1;
}

void dictionary_destructor_CMockStopIgnore(void)
{
  Mock.dictionary_destructor_IgnoreBool = (char)0;
}

void dictionary_destructor_CMockExpect(UNITY_LINE_TYPE cmock_line, struct Dictionary* dictionary)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dictionary_destructor_CALL_INSTANCE));
  CMOCK_dictionary_destructor_CALL_INSTANCE* cmock_call_instance = (CMOCK_dictionary_destructor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dictionary_destructor_CallInstance = CMock_Guts_MemChain(Mock.dictionary_destructor_CallInstance, cmock_guts_index);
  Mock.dictionary_destructor_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dictionary_destructor(cmock_call_instance, dictionary);
}

void dictionary_destructor_AddCallback(CMOCK_dictionary_destructor_CALLBACK Callback)
{
  Mock.dictionary_destructor_IgnoreBool = (char)0;
  Mock.dictionary_destructor_CallbackBool = (char)1;
  Mock.dictionary_destructor_CallbackFunctionPointer = Callback;
}

void dictionary_destructor_Stub(CMOCK_dictionary_destructor_CALLBACK Callback)
{
  Mock.dictionary_destructor_IgnoreBool = (char)0;
  Mock.dictionary_destructor_CallbackBool = (char)0;
  Mock.dictionary_destructor_CallbackFunctionPointer = Callback;
}

int compare_string_keys(void* entry_one, void* entry_two)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_compare_string_keys_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_compare_string_keys);
  cmock_call_instance = (CMOCK_compare_string_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.compare_string_keys_CallInstance);
  Mock.compare_string_keys_CallInstance = CMock_Guts_MemNext(Mock.compare_string_keys_CallInstance);
  if (Mock.compare_string_keys_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.compare_string_keys_FinalReturn;
    Mock.compare_string_keys_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.compare_string_keys_CallbackBool &&
      Mock.compare_string_keys_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.compare_string_keys_CallbackFunctionPointer(entry_one, entry_two, Mock.compare_string_keys_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_compare_string_keys,CMockString_entry_one);
    if (cmock_call_instance->Expected_entry_one == NULL)
      { UNITY_TEST_ASSERT_NULL(entry_one, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_entry_one, entry_one, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_compare_string_keys,CMockString_entry_two);
    if (cmock_call_instance->Expected_entry_two == NULL)
      { UNITY_TEST_ASSERT_NULL(entry_two, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_entry_two, entry_two, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.compare_string_keys_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_compare_string_keys);
    cmock_call_instance->ReturnVal = Mock.compare_string_keys_CallbackFunctionPointer(entry_one, entry_two, Mock.compare_string_keys_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_compare_string_keys(CMOCK_compare_string_keys_CALL_INSTANCE* cmock_call_instance, void* entry_one, void* entry_two);
void CMockExpectParameters_compare_string_keys(CMOCK_compare_string_keys_CALL_INSTANCE* cmock_call_instance, void* entry_one, void* entry_two)
{
  cmock_call_instance->Expected_entry_one = entry_one;
  cmock_call_instance->Expected_entry_two = entry_two;
}

void compare_string_keys_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_compare_string_keys_CALL_INSTANCE));
  CMOCK_compare_string_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_compare_string_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.compare_string_keys_CallInstance = CMock_Guts_MemChain(Mock.compare_string_keys_CallInstance, cmock_guts_index);
  Mock.compare_string_keys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.compare_string_keys_IgnoreBool = (char)1;
}

void compare_string_keys_CMockStopIgnore(void)
{
  if(Mock.compare_string_keys_IgnoreBool)
    Mock.compare_string_keys_CallInstance = CMock_Guts_MemNext(Mock.compare_string_keys_CallInstance);
  Mock.compare_string_keys_IgnoreBool = (char)0;
}

void compare_string_keys_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* entry_one, void* entry_two, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_compare_string_keys_CALL_INSTANCE));
  CMOCK_compare_string_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_compare_string_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.compare_string_keys_CallInstance = CMock_Guts_MemChain(Mock.compare_string_keys_CallInstance, cmock_guts_index);
  Mock.compare_string_keys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_compare_string_keys(cmock_call_instance, entry_one, entry_two);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void compare_string_keys_AddCallback(CMOCK_compare_string_keys_CALLBACK Callback)
{
  Mock.compare_string_keys_IgnoreBool = (char)0;
  Mock.compare_string_keys_CallbackBool = (char)1;
  Mock.compare_string_keys_CallbackFunctionPointer = Callback;
}

void compare_string_keys_Stub(CMOCK_compare_string_keys_CALLBACK Callback)
{
  Mock.compare_string_keys_IgnoreBool = (char)0;
  Mock.compare_string_keys_CallbackBool = (char)0;
  Mock.compare_string_keys_CallbackFunctionPointer = Callback;
}

