/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKNETWORK_H
#define _MOCKNETWORK_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "network.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocknetwork_Init(void);
void Mocknetwork_Destroy(void);
void Mocknetwork_Verify(void);




#define network_init_Ignore() TEST_FAIL_MESSAGE("network_init requires _IgnoreAndReturn");
#define network_init_IgnoreAndReturn(cmock_retval) network_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void network_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define network_init_StopIgnore() network_init_CMockStopIgnore()
void network_init_CMockStopIgnore(void);
#define network_init_Expect(port) TEST_FAIL_MESSAGE("network_init requires _ExpectAndReturn");
#define network_init_ExpectAndReturn(port, cmock_retval) network_init_CMockExpectAndReturn(__LINE__, port, cmock_retval)
void network_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int port, int cmock_to_return);
typedef int (* CMOCK_network_init_CALLBACK)(int port, int cmock_num_calls);
void network_init_AddCallback(CMOCK_network_init_CALLBACK Callback);
void network_init_Stub(CMOCK_network_init_CALLBACK Callback);
#define network_init_StubWithCallback network_init_Stub
#define network_run_server_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("network_run_server requires _Ignore (not AndReturn)");
#define network_run_server_Ignore() network_run_server_CMockIgnore()
void network_run_server_CMockIgnore(void);
#define network_run_server_StopIgnore() network_run_server_CMockStopIgnore()
void network_run_server_CMockStopIgnore(void);
#define network_run_server_ExpectAndReturn(server_fd, pl, routes, cmock_retval) TEST_FAIL_MESSAGE("network_run_server requires _Expect (not AndReturn)");
#define network_run_server_Expect(server_fd, pl, routes) network_run_server_CMockExpect(__LINE__, server_fd, pl, routes)
void network_run_server_CMockExpect(UNITY_LINE_TYPE cmock_line, int server_fd, thread_pool_t* pl, struct Dictionary* routes);
typedef void (* CMOCK_network_run_server_CALLBACK)(int server_fd, thread_pool_t* pl, struct Dictionary* routes, int cmock_num_calls);
void network_run_server_AddCallback(CMOCK_network_run_server_CALLBACK Callback);
void network_run_server_Stub(CMOCK_network_run_server_CALLBACK Callback);
#define network_run_server_StubWithCallback network_run_server_Stub
#define network_shutdown_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("network_shutdown requires _Ignore (not AndReturn)");
#define network_shutdown_Ignore() network_shutdown_CMockIgnore()
void network_shutdown_CMockIgnore(void);
#define network_shutdown_StopIgnore() network_shutdown_CMockStopIgnore()
void network_shutdown_CMockStopIgnore(void);
#define network_shutdown_ExpectAndReturn(server_fd, cmock_retval) TEST_FAIL_MESSAGE("network_shutdown requires _Expect (not AndReturn)");
#define network_shutdown_Expect(server_fd) network_shutdown_CMockExpect(__LINE__, server_fd)
void network_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line, int server_fd);
typedef void (* CMOCK_network_shutdown_CALLBACK)(int server_fd, int cmock_num_calls);
void network_shutdown_AddCallback(CMOCK_network_shutdown_CALLBACK Callback);
void network_shutdown_Stub(CMOCK_network_shutdown_CALLBACK Callback);
#define network_shutdown_StubWithCallback network_shutdown_Stub
#define send_all_Ignore() TEST_FAIL_MESSAGE("send_all requires _IgnoreAndReturn");
#define send_all_IgnoreAndReturn(cmock_retval) send_all_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void send_all_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define send_all_StopIgnore() send_all_CMockStopIgnore()
void send_all_CMockStopIgnore(void);
#define send_all_Expect(fd, buf, len) TEST_FAIL_MESSAGE("send_all requires _ExpectAndReturn");
#define send_all_ExpectAndReturn(fd, buf, len, cmock_retval) send_all_CMockExpectAndReturn(__LINE__, fd, buf, len, cmock_retval)
void send_all_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, const char* buf, int len, int cmock_to_return);
typedef int (* CMOCK_send_all_CALLBACK)(int fd, const char* buf, int len, int cmock_num_calls);
void send_all_AddCallback(CMOCK_send_all_CALLBACK Callback);
void send_all_Stub(CMOCK_send_all_CALLBACK Callback);
#define send_all_StubWithCallback send_all_Stub
#define send_file_Ignore() TEST_FAIL_MESSAGE("send_file requires _IgnoreAndReturn");
#define send_file_IgnoreAndReturn(cmock_retval) send_file_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void send_file_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define send_file_StopIgnore() send_file_CMockStopIgnore()
void send_file_CMockStopIgnore(void);
#define send_file_Expect(fd, file_fd, offset, len) TEST_FAIL_MESSAGE("send_file requires _ExpectAndReturn");
#define send_file_ExpectAndReturn(fd, file_fd, offset, len, cmock_retval) send_file_CMockExpectAndReturn(__LINE__, fd, file_fd, offset, len, cmock_retval)
void send_file_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, int file_fd, off_t offset, int len, int cmock_to_return);
typedef int (* CMOCK_send_file_CALLBACK)(int fd, int file_fd, off_t offset, int len, int cmock_num_calls);
void send_file_AddCallback(CMOCK_send_file_CALLBACK Callback);
void send_file_Stub(CMOCK_send_file_CALLBACK Callback);
#define send_file_StubWithCallback send_file_Stub
#define send_response_head_Ignore() TEST_FAIL_MESSAGE("send_response_head requires _IgnoreAndReturn");
#define send_response_head_IgnoreAndReturn(cmock_retval) send_response_head_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void send_response_head_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define send_response_head_StopIgnore() send_response_head_CMockStopIgnore()
void send_response_head_CMockStopIgnore(void);
#define send_response_head_Expect(fd, status, text, ct, cl, extra, ka) TEST_FAIL_MESSAGE("send_response_head requires _ExpectAndReturn");
#define send_response_head_ExpectAndReturn(fd, status, text, ct, cl, extra, ka, cmock_retval) send_response_head_CMockExpectAndReturn(__LINE__, fd, status, text, ct, cl, extra, ka, cmock_retval)
void send_response_head_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka, int cmock_to_return);
typedef int (* CMOCK_send_response_head_CALLBACK)(int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka, int cmock_num_calls);
void send_response_head_AddCallback(CMOCK_send_response_head_CALLBACK Callback);
void send_response_head_Stub(CMOCK_send_response_head_CALLBACK Callback);
#define send_response_head_StubWithCallback send_response_head_Stub
#define send_error_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_error requires _Ignore (not AndReturn)");
#define send_error_Ignore() send_error_CMockIgnore()
void send_error_CMockIgnore(void);
#define send_error_StopIgnore() send_error_CMockStopIgnore()
void send_error_CMockStopIgnore(void);
#define send_error_ExpectAndReturn(fd, code, cmock_retval) TEST_FAIL_MESSAGE("send_error requires _Expect (not AndReturn)");
#define send_error_Expect(fd, code) send_error_CMockExpect(__LINE__, fd, code)
void send_error_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, int code);
typedef void (* CMOCK_send_error_CALLBACK)(int fd, int code, int cmock_num_calls);
void send_error_AddCallback(CMOCK_send_error_CALLBACK Callback);
void send_error_Stub(CMOCK_send_error_CALLBACK Callback);
#define send_error_StubWithCallback send_error_Stub
#define send_not_modified_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_not_modified requires _Ignore (not AndReturn)");
#define send_not_modified_Ignore() send_not_modified_CMockIgnore()
void send_not_modified_CMockIgnore(void);
#define send_not_modified_StopIgnore() send_not_modified_CMockStopIgnore()
void send_not_modified_CMockStopIgnore(void);
#define send_not_modified_ExpectAndReturn(fd, last_modified, ka, cmock_retval) TEST_FAIL_MESSAGE("send_not_modified requires _Expect (not AndReturn)");
#define send_not_modified_Expect(fd, last_modified, ka) send_not_modified_CMockExpect(__LINE__, fd, last_modified, ka)
void send_not_modified_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, const char* last_modified, int ka);
typedef void (* CMOCK_send_not_modified_CALLBACK)(int fd, const char* last_modified, int ka, int cmock_num_calls);
void send_not_modified_AddCallback(CMOCK_send_not_modified_CALLBACK Callback);
void send_not_modified_Stub(CMOCK_send_not_modified_CALLBACK Callback);
#define send_not_modified_StubWithCallback send_not_modified_Stub
#define send_created_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_created requires _Ignore (not AndReturn)");
#define send_created_Ignore() send_created_CMockIgnore()
void send_created_CMockIgnore(void);
#define send_created_StopIgnore() send_created_CMockStopIgnore()
void send_created_CMockStopIgnore(void);
#define send_created_ExpectAndReturn(fd, location, ka, cmock_retval) TEST_FAIL_MESSAGE("send_created requires _Expect (not AndReturn)");
#define send_created_Expect(fd, location, ka) send_created_CMockExpect(__LINE__, fd, location, ka)
void send_created_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, const char* location, int ka);
typedef void (* CMOCK_send_created_CALLBACK)(int fd, const char* location, int ka, int cmock_num_calls);
void send_created_AddCallback(CMOCK_send_created_CALLBACK Callback);
void send_created_Stub(CMOCK_send_created_CALLBACK Callback);
#define send_created_StubWithCallback send_created_Stub
#define make_nonblocking_Ignore() TEST_FAIL_MESSAGE("make_nonblocking requires _IgnoreAndReturn");
#define make_nonblocking_IgnoreAndReturn(cmock_retval) make_nonblocking_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void make_nonblocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define make_nonblocking_StopIgnore() make_nonblocking_CMockStopIgnore()
void make_nonblocking_CMockStopIgnore(void);
#define make_nonblocking_Expect(sockfd) TEST_FAIL_MESSAGE("make_nonblocking requires _ExpectAndReturn");
#define make_nonblocking_ExpectAndReturn(sockfd, cmock_retval) make_nonblocking_CMockExpectAndReturn(__LINE__, sockfd, cmock_retval)
void make_nonblocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sockfd, int cmock_to_return);
typedef int (* CMOCK_make_nonblocking_CALLBACK)(int sockfd, int cmock_num_calls);
void make_nonblocking_AddCallback(CMOCK_make_nonblocking_CALLBACK Callback);
void make_nonblocking_Stub(CMOCK_make_nonblocking_CALLBACK Callback);
#define make_nonblocking_StubWithCallback make_nonblocking_Stub
#define setup_signals_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("setup_signals requires _Ignore (not AndReturn)");
#define setup_signals_Ignore() setup_signals_CMockIgnore()
void setup_signals_CMockIgnore(void);
#define setup_signals_StopIgnore() setup_signals_CMockStopIgnore()
void setup_signals_CMockStopIgnore(void);
#define setup_signals_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("setup_signals requires _Expect (not AndReturn)");
#define setup_signals_Expect() setup_signals_CMockExpect(__LINE__)
void setup_signals_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_setup_signals_CALLBACK)(int cmock_num_calls);
void setup_signals_AddCallback(CMOCK_setup_signals_CALLBACK Callback);
void setup_signals_Stub(CMOCK_setup_signals_CALLBACK Callback);
#define setup_signals_StubWithCallback setup_signals_Stub
#define check_keepalive_timeouts_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("check_keepalive_timeouts requires _Ignore (not AndReturn)");
#define check_keepalive_timeouts_Ignore() check_keepalive_timeouts_CMockIgnore()
void check_keepalive_timeouts_CMockIgnore(void);
#define check_keepalive_timeouts_StopIgnore() check_keepalive_timeouts_CMockStopIgnore()
void check_keepalive_timeouts_CMockStopIgnore(void);
#define check_keepalive_timeouts_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("check_keepalive_timeouts requires _Expect (not AndReturn)");
#define check_keepalive_timeouts_Expect() check_keepalive_timeouts_CMockExpect(__LINE__)
void check_keepalive_timeouts_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_check_keepalive_timeouts_CALLBACK)(int cmock_num_calls);
void check_keepalive_timeouts_AddCallback(CMOCK_check_keepalive_timeouts_CALLBACK Callback);
void check_keepalive_timeouts_Stub(CMOCK_check_keepalive_timeouts_CALLBACK Callback);
#define check_keepalive_timeouts_StubWithCallback check_keepalive_timeouts_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
