/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocklogger.h"

static const char* CMockString_client_ip = "client_ip";
static const char* CMockString_filepath = "filepath";
static const char* CMockString_host = "host";
static const char* CMockString_logger_destroy = "logger_destroy";
static const char* CMockString_logger_init = "logger_init";
static const char* CMockString_logger_log_request = "logger_log_request";
static const char* CMockString_method = "method";
static const char* CMockString_path = "path";
static const char* CMockString_status_code = "status_code";

typedef struct _CMOCK_logger_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_filepath;

} CMOCK_logger_init_CALL_INSTANCE;

typedef struct _CMOCK_logger_log_request_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_client_ip;
  const char* Expected_method;
  const char* Expected_path;
  int Expected_status_code;
  const char* Expected_host;

} CMOCK_logger_log_request_CALL_INSTANCE;

typedef struct _CMOCK_logger_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_logger_destroy_CALL_INSTANCE;

static struct MockloggerInstance
{
  char logger_init_IgnoreBool;
  int logger_init_FinalReturn;
  char logger_init_CallbackBool;
  CMOCK_logger_init_CALLBACK logger_init_CallbackFunctionPointer;
  int logger_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE logger_init_CallInstance;
  char logger_log_request_IgnoreBool;
  char logger_log_request_CallbackBool;
  CMOCK_logger_log_request_CALLBACK logger_log_request_CallbackFunctionPointer;
  int logger_log_request_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE logger_log_request_CallInstance;
  char logger_destroy_IgnoreBool;
  char logger_destroy_CallbackBool;
  CMOCK_logger_destroy_CALLBACK logger_destroy_CallbackFunctionPointer;
  int logger_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE logger_destroy_CallInstance;
} Mock;


void Mocklogger_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.logger_init_CallInstance;
  if (Mock.logger_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_logger_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.logger_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.logger_log_request_CallInstance;
  if (Mock.logger_log_request_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_logger_log_request);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.logger_log_request_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.logger_destroy_CallInstance;
  if (Mock.logger_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_logger_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.logger_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocklogger_Init(void)
{
  Mocklogger_Destroy();
}

void Mocklogger_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int logger_init(const char* filepath)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_logger_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_logger_init);
  cmock_call_instance = (CMOCK_logger_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.logger_init_CallInstance);
  Mock.logger_init_CallInstance = CMock_Guts_MemNext(Mock.logger_init_CallInstance);
  if (Mock.logger_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.logger_init_FinalReturn;
    Mock.logger_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.logger_init_CallbackBool &&
      Mock.logger_init_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.logger_init_CallbackFunctionPointer(filepath, Mock.logger_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_logger_init,CMockString_filepath);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filepath, filepath, cmock_line, CMockStringMismatch);
  }
  if (Mock.logger_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_logger_init);
    cmock_call_instance->ReturnVal = Mock.logger_init_CallbackFunctionPointer(filepath, Mock.logger_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_logger_init(CMOCK_logger_init_CALL_INSTANCE* cmock_call_instance, const char* filepath);
void CMockExpectParameters_logger_init(CMOCK_logger_init_CALL_INSTANCE* cmock_call_instance, const char* filepath)
{
  cmock_call_instance->Expected_filepath = filepath;
}

void logger_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logger_init_CALL_INSTANCE));
  CMOCK_logger_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_logger_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logger_init_CallInstance = CMock_Guts_MemChain(Mock.logger_init_CallInstance, cmock_guts_index);
  Mock.logger_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.logger_init_IgnoreBool = (char)1;
}

void logger_init_CMockStopIgnore(void)
{
  if(Mock.logger_init_IgnoreBool)
    Mock.logger_init_CallInstance = CMock_Guts_MemNext(Mock.logger_init_CallInstance);
  Mock.logger_init_IgnoreBool = (char)0;
}

void logger_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filepath, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logger_init_CALL_INSTANCE));
  CMOCK_logger_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_logger_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logger_init_CallInstance = CMock_Guts_MemChain(Mock.logger_init_CallInstance, cmock_guts_index);
  Mock.logger_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_logger_init(cmock_call_instance, filepath);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void logger_init_AddCallback(CMOCK_logger_init_CALLBACK Callback)
{
  Mock.logger_init_IgnoreBool = (char)0;
  Mock.logger_init_CallbackBool = (char)1;
  Mock.logger_init_CallbackFunctionPointer = Callback;
}

void logger_init_Stub(CMOCK_logger_init_CALLBACK Callback)
{
  Mock.logger_init_IgnoreBool = (char)0;
  Mock.logger_init_CallbackBool = (char)0;
  Mock.logger_init_CallbackFunctionPointer = Callback;
}

void logger_log_request(const char* client_ip, const char* method, const char* path, int status_code, const char* host)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_logger_log_request_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_logger_log_request);
  cmock_call_instance = (CMOCK_logger_log_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.logger_log_request_CallInstance);
  Mock.logger_log_request_CallInstance = CMock_Guts_MemNext(Mock.logger_log_request_CallInstance);
  if (Mock.logger_log_request_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.logger_log_request_CallbackBool &&
      Mock.logger_log_request_CallbackFunctionPointer != NULL)
  {
    Mock.logger_log_request_CallbackFunctionPointer(client_ip, method, path, status_code, host, Mock.logger_log_request_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_logger_log_request,CMockString_client_ip);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_client_ip, client_ip, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logger_log_request,CMockString_method);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_method, method, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logger_log_request,CMockString_path);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_path, path, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logger_log_request,CMockString_status_code);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_status_code, status_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logger_log_request,CMockString_host);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_host, host, cmock_line, CMockStringMismatch);
  }
  if (Mock.logger_log_request_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_logger_log_request);
    Mock.logger_log_request_CallbackFunctionPointer(client_ip, method, path, status_code, host, Mock.logger_log_request_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_logger_log_request(CMOCK_logger_log_request_CALL_INSTANCE* cmock_call_instance, const char* client_ip, const char* method, const char* path, int status_code, const char* host);
void CMockExpectParameters_logger_log_request(CMOCK_logger_log_request_CALL_INSTANCE* cmock_call_instance, const char* client_ip, const char* method, const char* path, int status_code, const char* host)
{
  cmock_call_instance->Expected_client_ip = client_ip;
  cmock_call_instance->Expected_method = method;
  cmock_call_instance->Expected_path = path;
  cmock_call_instance->Expected_status_code = status_code;
  cmock_call_instance->Expected_host = host;
}

void logger_log_request_CMockIgnore(void)
{
  Mock.logger_log_request_IgnoreBool = (char)1;
}

void logger_log_request_CMockStopIgnore(void)
{
  Mock.logger_log_request_IgnoreBool = (char)0;
}

void logger_log_request_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* client_ip, const char* method, const char* path, int status_code, const char* host)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logger_log_request_CALL_INSTANCE));
  CMOCK_logger_log_request_CALL_INSTANCE* cmock_call_instance = (CMOCK_logger_log_request_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logger_log_request_CallInstance = CMock_Guts_MemChain(Mock.logger_log_request_CallInstance, cmock_guts_index);
  Mock.logger_log_request_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_logger_log_request(cmock_call_instance, client_ip, method, path, status_code, host);
}

void logger_log_request_AddCallback(CMOCK_logger_log_request_CALLBACK Callback)
{
  Mock.logger_log_request_IgnoreBool = (char)0;
  Mock.logger_log_request_CallbackBool = (char)1;
  Mock.logger_log_request_CallbackFunctionPointer = Callback;
}

void logger_log_request_Stub(CMOCK_logger_log_request_CALLBACK Callback)
{
  Mock.logger_log_request_IgnoreBool = (char)0;
  Mock.logger_log_request_CallbackBool = (char)0;
  Mock.logger_log_request_CallbackFunctionPointer = Callback;
}

void logger_destroy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_logger_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_logger_destroy);
  cmock_call_instance = (CMOCK_logger_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.logger_destroy_CallInstance);
  Mock.logger_destroy_CallInstance = CMock_Guts_MemNext(Mock.logger_destroy_CallInstance);
  if (Mock.logger_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.logger_destroy_CallbackBool &&
      Mock.logger_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.logger_destroy_CallbackFunctionPointer(Mock.logger_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.logger_destroy_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_logger_destroy);
    Mock.logger_destroy_CallbackFunctionPointer(Mock.logger_destroy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void logger_destroy_CMockIgnore(void)
{
  Mock.logger_destroy_IgnoreBool = (char)1;
}

void logger_destroy_CMockStopIgnore(void)
{
  Mock.logger_destroy_IgnoreBool = (char)0;
}

void logger_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logger_destroy_CALL_INSTANCE));
  CMOCK_logger_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_logger_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logger_destroy_CallInstance = CMock_Guts_MemChain(Mock.logger_destroy_CallInstance, cmock_guts_index);
  Mock.logger_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void logger_destroy_AddCallback(CMOCK_logger_destroy_CALLBACK Callback)
{
  Mock.logger_destroy_IgnoreBool = (char)0;
  Mock.logger_destroy_CallbackBool = (char)1;
  Mock.logger_destroy_CallbackFunctionPointer = Callback;
}

void logger_destroy_Stub(CMOCK_logger_destroy_CALLBACK Callback)
{
  Mock.logger_destroy_IgnoreBool = (char)0;
  Mock.logger_destroy_CallbackBool = (char)0;
  Mock.logger_destroy_CallbackFunctionPointer = Callback;
}

