/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTHREAD_POOL_H
#define _MOCKTHREAD_POOL_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "thread_pool.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockthread_pool_Init(void);
void Mockthread_pool_Destroy(void);
void Mockthread_pool_Verify(void);




#define thread_pool_init_Ignore() TEST_FAIL_MESSAGE("thread_pool_init requires _IgnoreAndReturn");
#define thread_pool_init_IgnoreAndReturn(cmock_retval) thread_pool_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void thread_pool_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define thread_pool_init_StopIgnore() thread_pool_init_CMockStopIgnore()
void thread_pool_init_CMockStopIgnore(void);
#define thread_pool_init_Expect(thrd_pl, max_thread_num, size_option, pool_name) TEST_FAIL_MESSAGE("thread_pool_init requires _ExpectAndReturn");
#define thread_pool_init_ExpectAndReturn(thrd_pl, max_thread_num, size_option, pool_name, cmock_retval) thread_pool_init_CMockExpectAndReturn(__LINE__, thrd_pl, max_thread_num, size_option, pool_name, cmock_retval)
void thread_pool_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name, int cmock_to_return);
typedef int (* CMOCK_thread_pool_init_CALLBACK)(thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name, int cmock_num_calls);
void thread_pool_init_AddCallback(CMOCK_thread_pool_init_CALLBACK Callback);
void thread_pool_init_Stub(CMOCK_thread_pool_init_CALLBACK Callback);
#define thread_pool_init_StubWithCallback thread_pool_init_Stub
#define add_work_Ignore() TEST_FAIL_MESSAGE("add_work requires _IgnoreAndReturn");
#define add_work_IgnoreAndReturn(cmock_retval) add_work_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void add_work_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define add_work_StopIgnore() add_work_CMockStopIgnore()
void add_work_CMockStopIgnore(void);
#define add_work_Expect(thrd_pl, task) TEST_FAIL_MESSAGE("add_work requires _ExpectAndReturn");
#define add_work_ExpectAndReturn(thrd_pl, task, cmock_retval) add_work_CMockExpectAndReturn(__LINE__, thrd_pl, task, cmock_retval)
void add_work_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, struct ClientTask* task, int cmock_to_return);
typedef int (* CMOCK_add_work_CALLBACK)(thread_pool_t* thrd_pl, struct ClientTask* task, int cmock_num_calls);
void add_work_AddCallback(CMOCK_add_work_CALLBACK Callback);
void add_work_Stub(CMOCK_add_work_CALLBACK Callback);
#define add_work_StubWithCallback add_work_Stub
#define _thread_task_Ignore() TEST_FAIL_MESSAGE("_thread_task requires _IgnoreAndReturn");
#define _thread_task_IgnoreAndReturn(cmock_retval) _thread_task_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void _thread_task_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define _thread_task_StopIgnore() _thread_task_CMockStopIgnore()
void _thread_task_CMockStopIgnore(void);
#define _thread_task_Expect(arg) TEST_FAIL_MESSAGE("_thread_task requires _ExpectAndReturn");
#define _thread_task_ExpectAndReturn(arg, cmock_retval) _thread_task_CMockExpectAndReturn(__LINE__, arg, cmock_retval)
void _thread_task_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* arg, void* cmock_to_return);
typedef void* (* CMOCK__thread_task_CALLBACK)(void* arg, int cmock_num_calls);
void _thread_task_AddCallback(CMOCK__thread_task_CALLBACK Callback);
void _thread_task_Stub(CMOCK__thread_task_CALLBACK Callback);
#define _thread_task_StubWithCallback _thread_task_Stub
#define thread_pool_destroy_Ignore() TEST_FAIL_MESSAGE("thread_pool_destroy requires _IgnoreAndReturn");
#define thread_pool_destroy_IgnoreAndReturn(cmock_retval) thread_pool_destroy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void thread_pool_destroy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define thread_pool_destroy_StopIgnore() thread_pool_destroy_CMockStopIgnore()
void thread_pool_destroy_CMockStopIgnore(void);
#define thread_pool_destroy_Expect(thrd_pl, option) TEST_FAIL_MESSAGE("thread_pool_destroy requires _ExpectAndReturn");
#define thread_pool_destroy_ExpectAndReturn(thrd_pl, option, cmock_retval) thread_pool_destroy_CMockExpectAndReturn(__LINE__, thrd_pl, option, cmock_retval)
void thread_pool_destroy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, int option, int cmock_to_return);
typedef int (* CMOCK_thread_pool_destroy_CALLBACK)(thread_pool_t* thrd_pl, int option, int cmock_num_calls);
void thread_pool_destroy_AddCallback(CMOCK_thread_pool_destroy_CALLBACK Callback);
void thread_pool_destroy_Stub(CMOCK_thread_pool_destroy_CALLBACK Callback);
#define thread_pool_destroy_StubWithCallback thread_pool_destroy_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
