/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKLOGGER_H
#define _MOCKLOGGER_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "logger.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocklogger_Init(void);
void Mocklogger_Destroy(void);
void Mocklogger_Verify(void);




#define logger_init_Ignore() TEST_FAIL_MESSAGE("logger_init requires _IgnoreAndReturn");
#define logger_init_IgnoreAndReturn(cmock_retval) logger_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void logger_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define logger_init_StopIgnore() logger_init_CMockStopIgnore()
void logger_init_CMockStopIgnore(void);
#define logger_init_Expect(filepath) TEST_FAIL_MESSAGE("logger_init requires _ExpectAndReturn");
#define logger_init_ExpectAndReturn(filepath, cmock_retval) logger_init_CMockExpectAndReturn(__LINE__, filepath, cmock_retval)
void logger_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filepath, int cmock_to_return);
typedef int (* CMOCK_logger_init_CALLBACK)(const char* filepath, int cmock_num_calls);
void logger_init_AddCallback(CMOCK_logger_init_CALLBACK Callback);
void logger_init_Stub(CMOCK_logger_init_CALLBACK Callback);
#define logger_init_StubWithCallback logger_init_Stub
#define logger_log_request_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("logger_log_request requires _Ignore (not AndReturn)");
#define logger_log_request_Ignore() logger_log_request_CMockIgnore()
void logger_log_request_CMockIgnore(void);
#define logger_log_request_StopIgnore() logger_log_request_CMockStopIgnore()
void logger_log_request_CMockStopIgnore(void);
#define logger_log_request_ExpectAndReturn(client_ip, method, path, status_code, host, cmock_retval) TEST_FAIL_MESSAGE("logger_log_request requires _Expect (not AndReturn)");
#define logger_log_request_Expect(client_ip, method, path, status_code, host) logger_log_request_CMockExpect(__LINE__, client_ip, method, path, status_code, host)
void logger_log_request_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* client_ip, const char* method, const char* path, int status_code, const char* host);
typedef void (* CMOCK_logger_log_request_CALLBACK)(const char* client_ip, const char* method, const char* path, int status_code, const char* host, int cmock_num_calls);
void logger_log_request_AddCallback(CMOCK_logger_log_request_CALLBACK Callback);
void logger_log_request_Stub(CMOCK_logger_log_request_CALLBACK Callback);
#define logger_log_request_StubWithCallback logger_log_request_Stub
#define logger_destroy_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("logger_destroy requires _Ignore (not AndReturn)");
#define logger_destroy_Ignore() logger_destroy_CMockIgnore()
void logger_destroy_CMockIgnore(void);
#define logger_destroy_StopIgnore() logger_destroy_CMockStopIgnore()
void logger_destroy_CMockStopIgnore(void);
#define logger_destroy_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("logger_destroy requires _Expect (not AndReturn)");
#define logger_destroy_Expect() logger_destroy_CMockExpect(__LINE__)
void logger_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_logger_destroy_CALLBACK)(int cmock_num_calls);
void logger_destroy_AddCallback(CMOCK_logger_destroy_CALLBACK Callback);
void logger_destroy_Stub(CMOCK_logger_destroy_CALLBACK Callback);
#define logger_destroy_StubWithCallback logger_destroy_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
