/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFIFO_QUEUE_H
#define _MOCKFIFO_QUEUE_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "fifo_queue.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockfifo_queue_Init(void);
void Mockfifo_queue_Destroy(void);
void Mockfifo_queue_Verify(void);




#define fifo_queue_init_Ignore() TEST_FAIL_MESSAGE("fifo_queue_init requires _IgnoreAndReturn");
#define fifo_queue_init_IgnoreAndReturn(cmock_retval) fifo_queue_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void fifo_queue_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define fifo_queue_init_StopIgnore() fifo_queue_init_CMockStopIgnore()
void fifo_queue_init_CMockStopIgnore(void);
#define fifo_queue_init_Expect(queue) TEST_FAIL_MESSAGE("fifo_queue_init requires _ExpectAndReturn");
#define fifo_queue_init_ExpectAndReturn(queue, cmock_retval) fifo_queue_init_CMockExpectAndReturn(__LINE__, queue, cmock_retval)
void fifo_queue_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, int cmock_to_return);
typedef int (* CMOCK_fifo_queue_init_CALLBACK)(fifo_queue_t* queue, int cmock_num_calls);
void fifo_queue_init_AddCallback(CMOCK_fifo_queue_init_CALLBACK Callback);
void fifo_queue_init_Stub(CMOCK_fifo_queue_init_CALLBACK Callback);
#define fifo_queue_init_StubWithCallback fifo_queue_init_Stub
#define push_last_Ignore() TEST_FAIL_MESSAGE("push_last requires _IgnoreAndReturn");
#define push_last_IgnoreAndReturn(cmock_retval) push_last_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void push_last_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define push_last_StopIgnore() push_last_CMockStopIgnore()
void push_last_CMockStopIgnore(void);
#define push_last_Expect(queue, task) TEST_FAIL_MESSAGE("push_last requires _ExpectAndReturn");
#define push_last_ExpectAndReturn(queue, task, cmock_retval) push_last_CMockExpectAndReturn(__LINE__, queue, task, cmock_retval)
void push_last_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, struct ClientTask* task, int cmock_to_return);
typedef int (* CMOCK_push_last_CALLBACK)(fifo_queue_t* queue, struct ClientTask* task, int cmock_num_calls);
void push_last_AddCallback(CMOCK_push_last_CALLBACK Callback);
void push_last_Stub(CMOCK_push_last_CALLBACK Callback);
#define push_last_StubWithCallback push_last_Stub
#define pop_first_Ignore() TEST_FAIL_MESSAGE("pop_first requires _IgnoreAndReturn");
#define pop_first_IgnoreAndReturn(cmock_retval) pop_first_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void pop_first_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define pop_first_StopIgnore() pop_first_CMockStopIgnore()
void pop_first_CMockStopIgnore(void);
#define pop_first_Expect(queue, task) TEST_FAIL_MESSAGE("pop_first requires _ExpectAndReturn");
#define pop_first_ExpectAndReturn(queue, task, cmock_retval) pop_first_CMockExpectAndReturn(__LINE__, queue, task, cmock_retval)
void pop_first_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fifo_queue_t* queue, struct ClientTask** task, int cmock_to_return);
typedef int (* CMOCK_pop_first_CALLBACK)(fifo_queue_t* queue, struct ClientTask** task, int cmock_num_calls);
void pop_first_AddCallback(CMOCK_pop_first_CALLBACK Callback);
void pop_first_Stub(CMOCK_pop_first_CALLBACK Callback);
#define pop_first_StubWithCallback pop_first_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
