/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockthread_pool.h"

static const char* CMockString__thread_task = "_thread_task";
static const char* CMockString_add_work = "add_work";
static const char* CMockString_arg = "arg";
static const char* CMockString_max_thread_num = "max_thread_num";
static const char* CMockString_option = "option";
static const char* CMockString_pool_name = "pool_name";
static const char* CMockString_size_option = "size_option";
static const char* CMockString_task = "task";
static const char* CMockString_thrd_pl = "thrd_pl";
static const char* CMockString_thread_pool_destroy = "thread_pool_destroy";
static const char* CMockString_thread_pool_init = "thread_pool_init";

typedef struct _CMOCK_thread_pool_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  thread_pool_t* Expected_thrd_pl;
  int Expected_max_thread_num;
  int Expected_size_option;
  const char* Expected_pool_name;

} CMOCK_thread_pool_init_CALL_INSTANCE;

typedef struct _CMOCK_add_work_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  thread_pool_t* Expected_thrd_pl;
  struct ClientTask* Expected_task;

} CMOCK_add_work_CALL_INSTANCE;

typedef struct _CMOCK__thread_task_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  void* Expected_arg;

} CMOCK__thread_task_CALL_INSTANCE;

typedef struct _CMOCK_thread_pool_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  thread_pool_t* Expected_thrd_pl;
  int Expected_option;

} CMOCK_thread_pool_destroy_CALL_INSTANCE;

static struct Mockthread_poolInstance
{
  char thread_pool_init_IgnoreBool;
  int thread_pool_init_FinalReturn;
  char thread_pool_init_CallbackBool;
  CMOCK_thread_pool_init_CALLBACK thread_pool_init_CallbackFunctionPointer;
  int thread_pool_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE thread_pool_init_CallInstance;
  char add_work_IgnoreBool;
  int add_work_FinalReturn;
  char add_work_CallbackBool;
  CMOCK_add_work_CALLBACK add_work_CallbackFunctionPointer;
  int add_work_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE add_work_CallInstance;
  char _thread_task_IgnoreBool;
  void* _thread_task_FinalReturn;
  char _thread_task_CallbackBool;
  CMOCK__thread_task_CALLBACK _thread_task_CallbackFunctionPointer;
  int _thread_task_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE _thread_task_CallInstance;
  char thread_pool_destroy_IgnoreBool;
  int thread_pool_destroy_FinalReturn;
  char thread_pool_destroy_CallbackBool;
  CMOCK_thread_pool_destroy_CALLBACK thread_pool_destroy_CallbackFunctionPointer;
  int thread_pool_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE thread_pool_destroy_CallInstance;
} Mock;


void Mockthread_pool_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.thread_pool_init_CallInstance;
  if (Mock.thread_pool_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_thread_pool_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.thread_pool_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.add_work_CallInstance;
  if (Mock.add_work_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_add_work);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.add_work_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock._thread_task_CallInstance;
  if (Mock._thread_task_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString__thread_task);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock._thread_task_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.thread_pool_destroy_CallInstance;
  if (Mock.thread_pool_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_thread_pool_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.thread_pool_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockthread_pool_Init(void)
{
  Mockthread_pool_Destroy();
}

void Mockthread_pool_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int thread_pool_init(thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_thread_pool_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_thread_pool_init);
  cmock_call_instance = (CMOCK_thread_pool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.thread_pool_init_CallInstance);
  Mock.thread_pool_init_CallInstance = CMock_Guts_MemNext(Mock.thread_pool_init_CallInstance);
  if (Mock.thread_pool_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.thread_pool_init_FinalReturn;
    Mock.thread_pool_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.thread_pool_init_CallbackBool &&
      Mock.thread_pool_init_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.thread_pool_init_CallbackFunctionPointer(thrd_pl, max_thread_num, size_option, pool_name, Mock.thread_pool_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_init,CMockString_thrd_pl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_thrd_pl, thrd_pl, sizeof(thread_pool_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_init,CMockString_max_thread_num);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_max_thread_num, max_thread_num, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_init,CMockString_size_option);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_size_option, size_option, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_init,CMockString_pool_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pool_name, pool_name, cmock_line, CMockStringMismatch);
  }
  if (Mock.thread_pool_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_thread_pool_init);
    cmock_call_instance->ReturnVal = Mock.thread_pool_init_CallbackFunctionPointer(thrd_pl, max_thread_num, size_option, pool_name, Mock.thread_pool_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_thread_pool_init(CMOCK_thread_pool_init_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name);
void CMockExpectParameters_thread_pool_init(CMOCK_thread_pool_init_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name)
{
  cmock_call_instance->Expected_thrd_pl = thrd_pl;
  cmock_call_instance->Expected_max_thread_num = max_thread_num;
  cmock_call_instance->Expected_size_option = size_option;
  cmock_call_instance->Expected_pool_name = pool_name;
}

void thread_pool_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_thread_pool_init_CALL_INSTANCE));
  CMOCK_thread_pool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_thread_pool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.thread_pool_init_CallInstance = CMock_Guts_MemChain(Mock.thread_pool_init_CallInstance, cmock_guts_index);
  Mock.thread_pool_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.thread_pool_init_IgnoreBool = (char)1;
}

void thread_pool_init_CMockStopIgnore(void)
{
  if(Mock.thread_pool_init_IgnoreBool)
    Mock.thread_pool_init_CallInstance = CMock_Guts_MemNext(Mock.thread_pool_init_CallInstance);
  Mock.thread_pool_init_IgnoreBool = (char)0;
}

void thread_pool_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, int max_thread_num, int size_option, const char* pool_name, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_thread_pool_init_CALL_INSTANCE));
  CMOCK_thread_pool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_thread_pool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.thread_pool_init_CallInstance = CMock_Guts_MemChain(Mock.thread_pool_init_CallInstance, cmock_guts_index);
  Mock.thread_pool_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_thread_pool_init(cmock_call_instance, thrd_pl, max_thread_num, size_option, pool_name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void thread_pool_init_AddCallback(CMOCK_thread_pool_init_CALLBACK Callback)
{
  Mock.thread_pool_init_IgnoreBool = (char)0;
  Mock.thread_pool_init_CallbackBool = (char)1;
  Mock.thread_pool_init_CallbackFunctionPointer = Callback;
}

void thread_pool_init_Stub(CMOCK_thread_pool_init_CALLBACK Callback)
{
  Mock.thread_pool_init_IgnoreBool = (char)0;
  Mock.thread_pool_init_CallbackBool = (char)0;
  Mock.thread_pool_init_CallbackFunctionPointer = Callback;
}

int add_work(thread_pool_t* thrd_pl, struct ClientTask* task)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_add_work_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_add_work);
  cmock_call_instance = (CMOCK_add_work_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.add_work_CallInstance);
  Mock.add_work_CallInstance = CMock_Guts_MemNext(Mock.add_work_CallInstance);
  if (Mock.add_work_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.add_work_FinalReturn;
    Mock.add_work_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.add_work_CallbackBool &&
      Mock.add_work_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.add_work_CallbackFunctionPointer(thrd_pl, task, Mock.add_work_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_add_work,CMockString_thrd_pl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_thrd_pl, thrd_pl, sizeof(thread_pool_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_add_work,CMockString_task);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_task, task, sizeof(struct ClientTask), cmock_line, CMockStringMismatch);
  }
  if (Mock.add_work_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_add_work);
    cmock_call_instance->ReturnVal = Mock.add_work_CallbackFunctionPointer(thrd_pl, task, Mock.add_work_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_add_work(CMOCK_add_work_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, struct ClientTask* task);
void CMockExpectParameters_add_work(CMOCK_add_work_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, struct ClientTask* task)
{
  cmock_call_instance->Expected_thrd_pl = thrd_pl;
  cmock_call_instance->Expected_task = task;
}

void add_work_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_add_work_CALL_INSTANCE));
  CMOCK_add_work_CALL_INSTANCE* cmock_call_instance = (CMOCK_add_work_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.add_work_CallInstance = CMock_Guts_MemChain(Mock.add_work_CallInstance, cmock_guts_index);
  Mock.add_work_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.add_work_IgnoreBool = (char)1;
}

void add_work_CMockStopIgnore(void)
{
  if(Mock.add_work_IgnoreBool)
    Mock.add_work_CallInstance = CMock_Guts_MemNext(Mock.add_work_CallInstance);
  Mock.add_work_IgnoreBool = (char)0;
}

void add_work_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, struct ClientTask* task, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_add_work_CALL_INSTANCE));
  CMOCK_add_work_CALL_INSTANCE* cmock_call_instance = (CMOCK_add_work_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.add_work_CallInstance = CMock_Guts_MemChain(Mock.add_work_CallInstance, cmock_guts_index);
  Mock.add_work_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_add_work(cmock_call_instance, thrd_pl, task);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void add_work_AddCallback(CMOCK_add_work_CALLBACK Callback)
{
  Mock.add_work_IgnoreBool = (char)0;
  Mock.add_work_CallbackBool = (char)1;
  Mock.add_work_CallbackFunctionPointer = Callback;
}

void add_work_Stub(CMOCK_add_work_CALLBACK Callback)
{
  Mock.add_work_IgnoreBool = (char)0;
  Mock.add_work_CallbackBool = (char)0;
  Mock.add_work_CallbackFunctionPointer = Callback;
}

void* _thread_task(void* arg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK__thread_task_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString__thread_task);
  cmock_call_instance = (CMOCK__thread_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock._thread_task_CallInstance);
  Mock._thread_task_CallInstance = CMock_Guts_MemNext(Mock._thread_task_CallInstance);
  if (Mock._thread_task_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock._thread_task_FinalReturn;
    Mock._thread_task_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock._thread_task_CallbackBool &&
      Mock._thread_task_CallbackFunctionPointer != NULL)
  {
    void* cmock_cb_ret = Mock._thread_task_CallbackFunctionPointer(arg, Mock._thread_task_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString__thread_task,CMockString_arg);
    if (cmock_call_instance->Expected_arg == NULL)
      { UNITY_TEST_ASSERT_NULL(arg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_arg, arg, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock._thread_task_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString__thread_task);
    cmock_call_instance->ReturnVal = Mock._thread_task_CallbackFunctionPointer(arg, Mock._thread_task_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters__thread_task(CMOCK__thread_task_CALL_INSTANCE* cmock_call_instance, void* arg);
void CMockExpectParameters__thread_task(CMOCK__thread_task_CALL_INSTANCE* cmock_call_instance, void* arg)
{
  cmock_call_instance->Expected_arg = arg;
}

void _thread_task_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK__thread_task_CALL_INSTANCE));
  CMOCK__thread_task_CALL_INSTANCE* cmock_call_instance = (CMOCK__thread_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock._thread_task_CallInstance = CMock_Guts_MemChain(Mock._thread_task_CallInstance, cmock_guts_index);
  Mock._thread_task_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock._thread_task_IgnoreBool = (char)1;
}

void _thread_task_CMockStopIgnore(void)
{
  if(Mock._thread_task_IgnoreBool)
    Mock._thread_task_CallInstance = CMock_Guts_MemNext(Mock._thread_task_CallInstance);
  Mock._thread_task_IgnoreBool = (char)0;
}

void _thread_task_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* arg, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK__thread_task_CALL_INSTANCE));
  CMOCK__thread_task_CALL_INSTANCE* cmock_call_instance = (CMOCK__thread_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock._thread_task_CallInstance = CMock_Guts_MemChain(Mock._thread_task_CallInstance, cmock_guts_index);
  Mock._thread_task_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters__thread_task(cmock_call_instance, arg);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void _thread_task_AddCallback(CMOCK__thread_task_CALLBACK Callback)
{
  Mock._thread_task_IgnoreBool = (char)0;
  Mock._thread_task_CallbackBool = (char)1;
  Mock._thread_task_CallbackFunctionPointer = Callback;
}

void _thread_task_Stub(CMOCK__thread_task_CALLBACK Callback)
{
  Mock._thread_task_IgnoreBool = (char)0;
  Mock._thread_task_CallbackBool = (char)0;
  Mock._thread_task_CallbackFunctionPointer = Callback;
}

int thread_pool_destroy(thread_pool_t* thrd_pl, int option)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_thread_pool_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_thread_pool_destroy);
  cmock_call_instance = (CMOCK_thread_pool_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.thread_pool_destroy_CallInstance);
  Mock.thread_pool_destroy_CallInstance = CMock_Guts_MemNext(Mock.thread_pool_destroy_CallInstance);
  if (Mock.thread_pool_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.thread_pool_destroy_FinalReturn;
    Mock.thread_pool_destroy_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.thread_pool_destroy_CallbackBool &&
      Mock.thread_pool_destroy_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.thread_pool_destroy_CallbackFunctionPointer(thrd_pl, option, Mock.thread_pool_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_destroy,CMockString_thrd_pl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_thrd_pl, thrd_pl, sizeof(thread_pool_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_thread_pool_destroy,CMockString_option);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_option, option, cmock_line, CMockStringMismatch);
  }
  if (Mock.thread_pool_destroy_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_thread_pool_destroy);
    cmock_call_instance->ReturnVal = Mock.thread_pool_destroy_CallbackFunctionPointer(thrd_pl, option, Mock.thread_pool_destroy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_thread_pool_destroy(CMOCK_thread_pool_destroy_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, int option);
void CMockExpectParameters_thread_pool_destroy(CMOCK_thread_pool_destroy_CALL_INSTANCE* cmock_call_instance, thread_pool_t* thrd_pl, int option)
{
  cmock_call_instance->Expected_thrd_pl = thrd_pl;
  cmock_call_instance->Expected_option = option;
}

void thread_pool_destroy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_thread_pool_destroy_CALL_INSTANCE));
  CMOCK_thread_pool_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_thread_pool_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.thread_pool_destroy_CallInstance = CMock_Guts_MemChain(Mock.thread_pool_destroy_CallInstance, cmock_guts_index);
  Mock.thread_pool_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.thread_pool_destroy_IgnoreBool = (char)1;
}

void thread_pool_destroy_CMockStopIgnore(void)
{
  if(Mock.thread_pool_destroy_IgnoreBool)
    Mock.thread_pool_destroy_CallInstance = CMock_Guts_MemNext(Mock.thread_pool_destroy_CallInstance);
  Mock.thread_pool_destroy_IgnoreBool = (char)0;
}

void thread_pool_destroy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, thread_pool_t* thrd_pl, int option, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_thread_pool_destroy_CALL_INSTANCE));
  CMOCK_thread_pool_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_thread_pool_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.thread_pool_destroy_CallInstance = CMock_Guts_MemChain(Mock.thread_pool_destroy_CallInstance, cmock_guts_index);
  Mock.thread_pool_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_thread_pool_destroy(cmock_call_instance, thrd_pl, option);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void thread_pool_destroy_AddCallback(CMOCK_thread_pool_destroy_CALLBACK Callback)
{
  Mock.thread_pool_destroy_IgnoreBool = (char)0;
  Mock.thread_pool_destroy_CallbackBool = (char)1;
  Mock.thread_pool_destroy_CallbackFunctionPointer = Callback;
}

void thread_pool_destroy_Stub(CMOCK_thread_pool_destroy_CALLBACK Callback)
{
  Mock.thread_pool_destroy_IgnoreBool = (char)0;
  Mock.thread_pool_destroy_CallbackBool = (char)0;
  Mock.thread_pool_destroy_CallbackFunctionPointer = Callback;
}

