/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocknetwork.h"

static const char* CMockString_buf = "buf";
static const char* CMockString_check_keepalive_timeouts = "check_keepalive_timeouts";
static const char* CMockString_cl = "cl";
static const char* CMockString_code = "code";
static const char* CMockString_ct = "ct";
static const char* CMockString_extra = "extra";
static const char* CMockString_fd = "fd";
static const char* CMockString_file_fd = "file_fd";
static const char* CMockString_ka = "ka";
static const char* CMockString_last_modified = "last_modified";
static const char* CMockString_len = "len";
static const char* CMockString_location = "location";
static const char* CMockString_make_nonblocking = "make_nonblocking";
static const char* CMockString_network_init = "network_init";
static const char* CMockString_network_run_server = "network_run_server";
static const char* CMockString_network_shutdown = "network_shutdown";
static const char* CMockString_offset = "offset";
static const char* CMockString_pl = "pl";
static const char* CMockString_port = "port";
static const char* CMockString_routes = "routes";
static const char* CMockString_send_all = "send_all";
static const char* CMockString_send_created = "send_created";
static const char* CMockString_send_error = "send_error";
static const char* CMockString_send_file = "send_file";
static const char* CMockString_send_not_modified = "send_not_modified";
static const char* CMockString_send_response_head = "send_response_head";
static const char* CMockString_server_fd = "server_fd";
static const char* CMockString_setup_signals = "setup_signals";
static const char* CMockString_sockfd = "sockfd";
static const char* CMockString_status = "status";
static const char* CMockString_text = "text";

typedef struct _CMOCK_network_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_port;

} CMOCK_network_init_CALL_INSTANCE;

typedef struct _CMOCK_network_run_server_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_server_fd;
  thread_pool_t* Expected_pl;
  struct Dictionary* Expected_routes;

} CMOCK_network_run_server_CALL_INSTANCE;

typedef struct _CMOCK_network_shutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_server_fd;

} CMOCK_network_shutdown_CALL_INSTANCE;

typedef struct _CMOCK_send_all_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_fd;
  const char* Expected_buf;
  int Expected_len;

} CMOCK_send_all_CALL_INSTANCE;

typedef struct _CMOCK_send_file_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_fd;
  int Expected_file_fd;
  off_t Expected_offset;
  int Expected_len;

} CMOCK_send_file_CALL_INSTANCE;

typedef struct _CMOCK_send_response_head_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_fd;
  const char* Expected_status;
  const char* Expected_text;
  const char* Expected_ct;
  int Expected_cl;
  const char* Expected_extra;
  int Expected_ka;

} CMOCK_send_response_head_CALL_INSTANCE;

typedef struct _CMOCK_send_error_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_fd;
  int Expected_code;

} CMOCK_send_error_CALL_INSTANCE;

typedef struct _CMOCK_send_not_modified_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_fd;
  const char* Expected_last_modified;
  int Expected_ka;

} CMOCK_send_not_modified_CALL_INSTANCE;

typedef struct _CMOCK_send_created_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_fd;
  const char* Expected_location;
  int Expected_ka;

} CMOCK_send_created_CALL_INSTANCE;

typedef struct _CMOCK_make_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_sockfd;

} CMOCK_make_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_setup_signals_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_setup_signals_CALL_INSTANCE;

typedef struct _CMOCK_check_keepalive_timeouts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_check_keepalive_timeouts_CALL_INSTANCE;

static struct MocknetworkInstance
{
  char network_init_IgnoreBool;
  int network_init_FinalReturn;
  char network_init_CallbackBool;
  CMOCK_network_init_CALLBACK network_init_CallbackFunctionPointer;
  int network_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE network_init_CallInstance;
  char network_run_server_IgnoreBool;
  char network_run_server_CallbackBool;
  CMOCK_network_run_server_CALLBACK network_run_server_CallbackFunctionPointer;
  int network_run_server_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE network_run_server_CallInstance;
  char network_shutdown_IgnoreBool;
  char network_shutdown_CallbackBool;
  CMOCK_network_shutdown_CALLBACK network_shutdown_CallbackFunctionPointer;
  int network_shutdown_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE network_shutdown_CallInstance;
  char send_all_IgnoreBool;
  int send_all_FinalReturn;
  char send_all_CallbackBool;
  CMOCK_send_all_CALLBACK send_all_CallbackFunctionPointer;
  int send_all_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_all_CallInstance;
  char send_file_IgnoreBool;
  int send_file_FinalReturn;
  char send_file_CallbackBool;
  CMOCK_send_file_CALLBACK send_file_CallbackFunctionPointer;
  int send_file_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_file_CallInstance;
  char send_response_head_IgnoreBool;
  int send_response_head_FinalReturn;
  char send_response_head_CallbackBool;
  CMOCK_send_response_head_CALLBACK send_response_head_CallbackFunctionPointer;
  int send_response_head_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_response_head_CallInstance;
  char send_error_IgnoreBool;
  char send_error_CallbackBool;
  CMOCK_send_error_CALLBACK send_error_CallbackFunctionPointer;
  int send_error_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_error_CallInstance;
  char send_not_modified_IgnoreBool;
  char send_not_modified_CallbackBool;
  CMOCK_send_not_modified_CALLBACK send_not_modified_CallbackFunctionPointer;
  int send_not_modified_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_not_modified_CallInstance;
  char send_created_IgnoreBool;
  char send_created_CallbackBool;
  CMOCK_send_created_CALLBACK send_created_CallbackFunctionPointer;
  int send_created_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_created_CallInstance;
  char make_nonblocking_IgnoreBool;
  int make_nonblocking_FinalReturn;
  char make_nonblocking_CallbackBool;
  CMOCK_make_nonblocking_CALLBACK make_nonblocking_CallbackFunctionPointer;
  int make_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE make_nonblocking_CallInstance;
  char setup_signals_IgnoreBool;
  char setup_signals_CallbackBool;
  CMOCK_setup_signals_CALLBACK setup_signals_CallbackFunctionPointer;
  int setup_signals_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE setup_signals_CallInstance;
  char check_keepalive_timeouts_IgnoreBool;
  char check_keepalive_timeouts_CallbackBool;
  CMOCK_check_keepalive_timeouts_CALLBACK check_keepalive_timeouts_CallbackFunctionPointer;
  int check_keepalive_timeouts_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE check_keepalive_timeouts_CallInstance;
} Mock;


void Mocknetwork_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.network_init_CallInstance;
  if (Mock.network_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_network_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.network_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.network_run_server_CallInstance;
  if (Mock.network_run_server_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_network_run_server);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.network_run_server_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.network_shutdown_CallInstance;
  if (Mock.network_shutdown_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_network_shutdown);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.network_shutdown_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_all_CallInstance;
  if (Mock.send_all_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_all);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_all_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_file_CallInstance;
  if (Mock.send_file_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_file);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_file_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_response_head_CallInstance;
  if (Mock.send_response_head_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_response_head);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_response_head_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_error_CallInstance;
  if (Mock.send_error_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_error);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_error_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_not_modified_CallInstance;
  if (Mock.send_not_modified_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_not_modified);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_not_modified_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_created_CallInstance;
  if (Mock.send_created_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_created);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_created_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.make_nonblocking_CallInstance;
  if (Mock.make_nonblocking_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_make_nonblocking);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.make_nonblocking_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.setup_signals_CallInstance;
  if (Mock.setup_signals_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_setup_signals);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.setup_signals_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.check_keepalive_timeouts_CallInstance;
  if (Mock.check_keepalive_timeouts_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_check_keepalive_timeouts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.check_keepalive_timeouts_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocknetwork_Init(void)
{
  Mocknetwork_Destroy();
}

void Mocknetwork_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int network_init(int port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_network_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_network_init);
  cmock_call_instance = (CMOCK_network_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.network_init_CallInstance);
  Mock.network_init_CallInstance = CMock_Guts_MemNext(Mock.network_init_CallInstance);
  if (Mock.network_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.network_init_FinalReturn;
    Mock.network_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.network_init_CallbackBool &&
      Mock.network_init_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.network_init_CallbackFunctionPointer(port, Mock.network_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_network_init,CMockString_port);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_port, port, cmock_line, CMockStringMismatch);
  }
  if (Mock.network_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_network_init);
    cmock_call_instance->ReturnVal = Mock.network_init_CallbackFunctionPointer(port, Mock.network_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_network_init(CMOCK_network_init_CALL_INSTANCE* cmock_call_instance, int port);
void CMockExpectParameters_network_init(CMOCK_network_init_CALL_INSTANCE* cmock_call_instance, int port)
{
  cmock_call_instance->Expected_port = port;
}

void network_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_network_init_CALL_INSTANCE));
  CMOCK_network_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_network_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.network_init_CallInstance = CMock_Guts_MemChain(Mock.network_init_CallInstance, cmock_guts_index);
  Mock.network_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.network_init_IgnoreBool = (char)1;
}

void network_init_CMockStopIgnore(void)
{
  if(Mock.network_init_IgnoreBool)
    Mock.network_init_CallInstance = CMock_Guts_MemNext(Mock.network_init_CallInstance);
  Mock.network_init_IgnoreBool = (char)0;
}

void network_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int port, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_network_init_CALL_INSTANCE));
  CMOCK_network_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_network_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.network_init_CallInstance = CMock_Guts_MemChain(Mock.network_init_CallInstance, cmock_guts_index);
  Mock.network_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_network_init(cmock_call_instance, port);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void network_init_AddCallback(CMOCK_network_init_CALLBACK Callback)
{
  Mock.network_init_IgnoreBool = (char)0;
  Mock.network_init_CallbackBool = (char)1;
  Mock.network_init_CallbackFunctionPointer = Callback;
}

void network_init_Stub(CMOCK_network_init_CALLBACK Callback)
{
  Mock.network_init_IgnoreBool = (char)0;
  Mock.network_init_CallbackBool = (char)0;
  Mock.network_init_CallbackFunctionPointer = Callback;
}

void network_run_server(int server_fd, thread_pool_t* pl, struct Dictionary* routes)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_network_run_server_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_network_run_server);
  cmock_call_instance = (CMOCK_network_run_server_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.network_run_server_CallInstance);
  Mock.network_run_server_CallInstance = CMock_Guts_MemNext(Mock.network_run_server_CallInstance);
  if (Mock.network_run_server_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.network_run_server_CallbackBool &&
      Mock.network_run_server_CallbackFunctionPointer != NULL)
  {
    Mock.network_run_server_CallbackFunctionPointer(server_fd, pl, routes, Mock.network_run_server_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_network_run_server,CMockString_server_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_server_fd, server_fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_network_run_server,CMockString_pl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_pl, pl, sizeof(thread_pool_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_network_run_server,CMockString_routes);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_routes, routes, sizeof(struct Dictionary), cmock_line, CMockStringMismatch);
  }
  if (Mock.network_run_server_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_network_run_server);
    Mock.network_run_server_CallbackFunctionPointer(server_fd, pl, routes, Mock.network_run_server_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_network_run_server(CMOCK_network_run_server_CALL_INSTANCE* cmock_call_instance, int server_fd, thread_pool_t* pl, struct Dictionary* routes);
void CMockExpectParameters_network_run_server(CMOCK_network_run_server_CALL_INSTANCE* cmock_call_instance, int server_fd, thread_pool_t* pl, struct Dictionary* routes)
{
  cmock_call_instance->Expected_server_fd = server_fd;
  cmock_call_instance->Expected_pl = pl;
  cmock_call_instance->Expected_routes = routes;
}

void network_run_server_CMockIgnore(void)
{
  Mock.network_run_server_IgnoreBool = (char)1;
}

void network_run_server_CMockStopIgnore(void)
{
  Mock.network_run_server_IgnoreBool = (char)0;
}

void network_run_server_CMockExpect(UNITY_LINE_TYPE cmock_line, int server_fd, thread_pool_t* pl, struct Dictionary* routes)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_network_run_server_CALL_INSTANCE));
  CMOCK_network_run_server_CALL_INSTANCE* cmock_call_instance = (CMOCK_network_run_server_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.network_run_server_CallInstance = CMock_Guts_MemChain(Mock.network_run_server_CallInstance, cmock_guts_index);
  Mock.network_run_server_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_network_run_server(cmock_call_instance, server_fd, pl, routes);
}

void network_run_server_AddCallback(CMOCK_network_run_server_CALLBACK Callback)
{
  Mock.network_run_server_IgnoreBool = (char)0;
  Mock.network_run_server_CallbackBool = (char)1;
  Mock.network_run_server_CallbackFunctionPointer = Callback;
}

void network_run_server_Stub(CMOCK_network_run_server_CALLBACK Callback)
{
  Mock.network_run_server_IgnoreBool = (char)0;
  Mock.network_run_server_CallbackBool = (char)0;
  Mock.network_run_server_CallbackFunctionPointer = Callback;
}

void network_shutdown(int server_fd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_network_shutdown_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_network_shutdown);
  cmock_call_instance = (CMOCK_network_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.network_shutdown_CallInstance);
  Mock.network_shutdown_CallInstance = CMock_Guts_MemNext(Mock.network_shutdown_CallInstance);
  if (Mock.network_shutdown_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.network_shutdown_CallbackBool &&
      Mock.network_shutdown_CallbackFunctionPointer != NULL)
  {
    Mock.network_shutdown_CallbackFunctionPointer(server_fd, Mock.network_shutdown_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_network_shutdown,CMockString_server_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_server_fd, server_fd, cmock_line, CMockStringMismatch);
  }
  if (Mock.network_shutdown_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_network_shutdown);
    Mock.network_shutdown_CallbackFunctionPointer(server_fd, Mock.network_shutdown_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_network_shutdown(CMOCK_network_shutdown_CALL_INSTANCE* cmock_call_instance, int server_fd);
void CMockExpectParameters_network_shutdown(CMOCK_network_shutdown_CALL_INSTANCE* cmock_call_instance, int server_fd)
{
  cmock_call_instance->Expected_server_fd = server_fd;
}

void network_shutdown_CMockIgnore(void)
{
  Mock.network_shutdown_IgnoreBool = (char)1;
}

void network_shutdown_CMockStopIgnore(void)
{
  Mock.network_shutdown_IgnoreBool = (char)0;
}

void network_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line, int server_fd)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_network_shutdown_CALL_INSTANCE));
  CMOCK_network_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_network_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.network_shutdown_CallInstance = CMock_Guts_MemChain(Mock.network_shutdown_CallInstance, cmock_guts_index);
  Mock.network_shutdown_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_network_shutdown(cmock_call_instance, server_fd);
}

void network_shutdown_AddCallback(CMOCK_network_shutdown_CALLBACK Callback)
{
  Mock.network_shutdown_IgnoreBool = (char)0;
  Mock.network_shutdown_CallbackBool = (char)1;
  Mock.network_shutdown_CallbackFunctionPointer = Callback;
}

void network_shutdown_Stub(CMOCK_network_shutdown_CALLBACK Callback)
{
  Mock.network_shutdown_IgnoreBool = (char)0;
  Mock.network_shutdown_CallbackBool = (char)0;
  Mock.network_shutdown_CallbackFunctionPointer = Callback;
}

int send_all(int fd, const char* buf, int len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_all_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_all);
  cmock_call_instance = (CMOCK_send_all_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_all_CallInstance);
  Mock.send_all_CallInstance = CMock_Guts_MemNext(Mock.send_all_CallInstance);
  if (Mock.send_all_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.send_all_FinalReturn;
    Mock.send_all_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.send_all_CallbackBool &&
      Mock.send_all_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.send_all_CallbackFunctionPointer(fd, buf, len, Mock.send_all_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_all,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_all,CMockString_buf);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buf, buf, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_all,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_all_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_all);
    cmock_call_instance->ReturnVal = Mock.send_all_CallbackFunctionPointer(fd, buf, len, Mock.send_all_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_send_all(CMOCK_send_all_CALL_INSTANCE* cmock_call_instance, int fd, const char* buf, int len);
void CMockExpectParameters_send_all(CMOCK_send_all_CALL_INSTANCE* cmock_call_instance, int fd, const char* buf, int len)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->Expected_len = len;
}

void send_all_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_all_CALL_INSTANCE));
  CMOCK_send_all_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_all_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_all_CallInstance = CMock_Guts_MemChain(Mock.send_all_CallInstance, cmock_guts_index);
  Mock.send_all_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.send_all_IgnoreBool = (char)1;
}

void send_all_CMockStopIgnore(void)
{
  if(Mock.send_all_IgnoreBool)
    Mock.send_all_CallInstance = CMock_Guts_MemNext(Mock.send_all_CallInstance);
  Mock.send_all_IgnoreBool = (char)0;
}

void send_all_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, const char* buf, int len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_all_CALL_INSTANCE));
  CMOCK_send_all_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_all_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_all_CallInstance = CMock_Guts_MemChain(Mock.send_all_CallInstance, cmock_guts_index);
  Mock.send_all_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_all(cmock_call_instance, fd, buf, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void send_all_AddCallback(CMOCK_send_all_CALLBACK Callback)
{
  Mock.send_all_IgnoreBool = (char)0;
  Mock.send_all_CallbackBool = (char)1;
  Mock.send_all_CallbackFunctionPointer = Callback;
}

void send_all_Stub(CMOCK_send_all_CALLBACK Callback)
{
  Mock.send_all_IgnoreBool = (char)0;
  Mock.send_all_CallbackBool = (char)0;
  Mock.send_all_CallbackFunctionPointer = Callback;
}

int send_file(int fd, int file_fd, off_t offset, int len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_file_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_file);
  cmock_call_instance = (CMOCK_send_file_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_file_CallInstance);
  Mock.send_file_CallInstance = CMock_Guts_MemNext(Mock.send_file_CallInstance);
  if (Mock.send_file_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.send_file_FinalReturn;
    Mock.send_file_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.send_file_CallbackBool &&
      Mock.send_file_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.send_file_CallbackFunctionPointer(fd, file_fd, offset, len, Mock.send_file_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_file,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_file,CMockString_file_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_file_fd, file_fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_file,CMockString_offset);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_offset, &offset, sizeof(off_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_file,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_file_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_file);
    cmock_call_instance->ReturnVal = Mock.send_file_CallbackFunctionPointer(fd, file_fd, offset, len, Mock.send_file_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_send_file(CMOCK_send_file_CALL_INSTANCE* cmock_call_instance, int fd, int file_fd, off_t offset, int len);
void CMockExpectParameters_send_file(CMOCK_send_file_CALL_INSTANCE* cmock_call_instance, int fd, int file_fd, off_t offset, int len)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_file_fd = file_fd;
  memcpy((void*)(&cmock_call_instance->Expected_offset), (const void*)(&offset),
         sizeof(off_t[sizeof(offset) == sizeof(off_t) ? 1 : -1])); /* add off_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_len = len;
}

void send_file_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_file_CALL_INSTANCE));
  CMOCK_send_file_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_file_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_file_CallInstance = CMock_Guts_MemChain(Mock.send_file_CallInstance, cmock_guts_index);
  Mock.send_file_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.send_file_IgnoreBool = (char)1;
}

void send_file_CMockStopIgnore(void)
{
  if(Mock.send_file_IgnoreBool)
    Mock.send_file_CallInstance = CMock_Guts_MemNext(Mock.send_file_CallInstance);
  Mock.send_file_IgnoreBool = (char)0;
}

void send_file_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, int file_fd, off_t offset, int len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_file_CALL_INSTANCE));
  CMOCK_send_file_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_file_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_file_CallInstance = CMock_Guts_MemChain(Mock.send_file_CallInstance, cmock_guts_index);
  Mock.send_file_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_file(cmock_call_instance, fd, file_fd, offset, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void send_file_AddCallback(CMOCK_send_file_CALLBACK Callback)
{
  Mock.send_file_IgnoreBool = (char)0;
  Mock.send_file_CallbackBool = (char)1;
  Mock.send_file_CallbackFunctionPointer = Callback;
}

void send_file_Stub(CMOCK_send_file_CALLBACK Callback)
{
  Mock.send_file_IgnoreBool = (char)0;
  Mock.send_file_CallbackBool = (char)0;
  Mock.send_file_CallbackFunctionPointer = Callback;
}

int send_response_head(int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_response_head_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_response_head);
  cmock_call_instance = (CMOCK_send_response_head_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_response_head_CallInstance);
  Mock.send_response_head_CallInstance = CMock_Guts_MemNext(Mock.send_response_head_CallInstance);
  if (Mock.send_response_head_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.send_response_head_FinalReturn;
    Mock.send_response_head_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.send_response_head_CallbackBool &&
      Mock.send_response_head_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.send_response_head_CallbackFunctionPointer(fd, status, text, ct, cl, extra, ka, Mock.send_response_head_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_status);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_status, status, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_ct);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_ct, ct, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_cl);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_cl, cl, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_extra);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_extra, extra, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_response_head,CMockString_ka);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_ka, ka, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_response_head_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_response_head);
    cmock_call_instance->ReturnVal = Mock.send_response_head_CallbackFunctionPointer(fd, status, text, ct, cl, extra, ka, Mock.send_response_head_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_send_response_head(CMOCK_send_response_head_CALL_INSTANCE* cmock_call_instance, int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka);
void CMockExpectParameters_send_response_head(CMOCK_send_response_head_CALL_INSTANCE* cmock_call_instance, int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_status = status;
  cmock_call_instance->Expected_text = text;
  cmock_call_instance->Expected_ct = ct;
  cmock_call_instance->Expected_cl = cl;
  cmock_call_instance->Expected_extra = extra;
  cmock_call_instance->Expected_ka = ka;
}

void send_response_head_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_response_head_CALL_INSTANCE));
  CMOCK_send_response_head_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_response_head_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_response_head_CallInstance = CMock_Guts_MemChain(Mock.send_response_head_CallInstance, cmock_guts_index);
  Mock.send_response_head_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.send_response_head_IgnoreBool = (char)1;
}

void send_response_head_CMockStopIgnore(void)
{
  if(Mock.send_response_head_IgnoreBool)
    Mock.send_response_head_CallInstance = CMock_Guts_MemNext(Mock.send_response_head_CallInstance);
  Mock.send_response_head_IgnoreBool = (char)0;
}

void send_response_head_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int fd, const char* status, const char* text, const char* ct, int cl, const char* extra, int ka, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_response_head_CALL_INSTANCE));
  CMOCK_send_response_head_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_response_head_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_response_head_CallInstance = CMock_Guts_MemChain(Mock.send_response_head_CallInstance, cmock_guts_index);
  Mock.send_response_head_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_response_head(cmock_call_instance, fd, status, text, ct, cl, extra, ka);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void send_response_head_AddCallback(CMOCK_send_response_head_CALLBACK Callback)
{
  Mock.send_response_head_IgnoreBool = (char)0;
  Mock.send_response_head_CallbackBool = (char)1;
  Mock.send_response_head_CallbackFunctionPointer = Callback;
}

void send_response_head_Stub(CMOCK_send_response_head_CALLBACK Callback)
{
  Mock.send_response_head_IgnoreBool = (char)0;
  Mock.send_response_head_CallbackBool = (char)0;
  Mock.send_response_head_CallbackFunctionPointer = Callback;
}

void send_error(int fd, int code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_error_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_error);
  cmock_call_instance = (CMOCK_send_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_error_CallInstance);
  Mock.send_error_CallInstance = CMock_Guts_MemNext(Mock.send_error_CallInstance);
  if (Mock.send_error_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.send_error_CallbackBool &&
      Mock.send_error_CallbackFunctionPointer != NULL)
  {
    Mock.send_error_CallbackFunctionPointer(fd, code, Mock.send_error_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_error,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_error,CMockString_code);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_code, code, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_error_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_error);
    Mock.send_error_CallbackFunctionPointer(fd, code, Mock.send_error_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_send_error(CMOCK_send_error_CALL_INSTANCE* cmock_call_instance, int fd, int code);
void CMockExpectParameters_send_error(CMOCK_send_error_CALL_INSTANCE* cmock_call_instance, int fd, int code)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_code = code;
}

void send_error_CMockIgnore(void)
{
  Mock.send_error_IgnoreBool = (char)1;
}

void send_error_CMockStopIgnore(void)
{
  Mock.send_error_IgnoreBool = (char)0;
}

void send_error_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, int code)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_error_CALL_INSTANCE));
  CMOCK_send_error_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_error_CallInstance = CMock_Guts_MemChain(Mock.send_error_CallInstance, cmock_guts_index);
  Mock.send_error_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_error(cmock_call_instance, fd, code);
}

void send_error_AddCallback(CMOCK_send_error_CALLBACK Callback)
{
  Mock.send_error_IgnoreBool = (char)0;
  Mock.send_error_CallbackBool = (char)1;
  Mock.send_error_CallbackFunctionPointer = Callback;
}

void send_error_Stub(CMOCK_send_error_CALLBACK Callback)
{
  Mock.send_error_IgnoreBool = (char)0;
  Mock.send_error_CallbackBool = (char)0;
  Mock.send_error_CallbackFunctionPointer = Callback;
}

void send_not_modified(int fd, const char* last_modified, int ka)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_not_modified_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_not_modified);
  cmock_call_instance = (CMOCK_send_not_modified_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_not_modified_CallInstance);
  Mock.send_not_modified_CallInstance = CMock_Guts_MemNext(Mock.send_not_modified_CallInstance);
  if (Mock.send_not_modified_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.send_not_modified_CallbackBool &&
      Mock.send_not_modified_CallbackFunctionPointer != NULL)
  {
    Mock.send_not_modified_CallbackFunctionPointer(fd, last_modified, ka, Mock.send_not_modified_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_not_modified,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_not_modified,CMockString_last_modified);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_last_modified, last_modified, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_not_modified,CMockString_ka);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_ka, ka, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_not_modified_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_not_modified);
    Mock.send_not_modified_CallbackFunctionPointer(fd, last_modified, ka, Mock.send_not_modified_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_send_not_modified(CMOCK_send_not_modified_CALL_INSTANCE* cmock_call_instance, int fd, const char* last_modified, int ka);
void CMockExpectParameters_send_not_modified(CMOCK_send_not_modified_CALL_INSTANCE* cmock_call_instance, int fd, const char* last_modified, int ka)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_last_modified = last_modified;
  cmock_call_instance->Expected_ka = ka;
}

void send_not_modified_CMockIgnore(void)
{
  Mock.send_not_modified_IgnoreBool = (char)1;
}

void send_not_modified_CMockStopIgnore(void)
{
  Mock.send_not_modified_IgnoreBool = (char)0;
}

void send_not_modified_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, const char* last_modified, int ka)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_not_modified_CALL_INSTANCE));
  CMOCK_send_not_modified_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_not_modified_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_not_modified_CallInstance = CMock_Guts_MemChain(Mock.send_not_modified_CallInstance, cmock_guts_index);
  Mock.send_not_modified_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_not_modified(cmock_call_instance, fd, last_modified, ka);
}

void send_not_modified_AddCallback(CMOCK_send_not_modified_CALLBACK Callback)
{
  Mock.send_not_modified_IgnoreBool = (char)0;
  Mock.send_not_modified_CallbackBool = (char)1;
  Mock.send_not_modified_CallbackFunctionPointer = Callback;
}

void send_not_modified_Stub(CMOCK_send_not_modified_CALLBACK Callback)
{
  Mock.send_not_modified_IgnoreBool = (char)0;
  Mock.send_not_modified_CallbackBool = (char)0;
  Mock.send_not_modified_CallbackFunctionPointer = Callback;
}

void send_created(int fd, const char* location, int ka)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_created_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_created);
  cmock_call_instance = (CMOCK_send_created_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_created_CallInstance);
  Mock.send_created_CallInstance = CMock_Guts_MemNext(Mock.send_created_CallInstance);
  if (Mock.send_created_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.send_created_CallbackBool &&
      Mock.send_created_CallbackFunctionPointer != NULL)
  {
    Mock.send_created_CallbackFunctionPointer(fd, location, ka, Mock.send_created_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_send_created,CMockString_fd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_fd, fd, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_created,CMockString_location);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_location, location, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_send_created,CMockString_ka);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_ka, ka, cmock_line, CMockStringMismatch);
  }
  if (Mock.send_created_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_created);
    Mock.send_created_CallbackFunctionPointer(fd, location, ka, Mock.send_created_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_send_created(CMOCK_send_created_CALL_INSTANCE* cmock_call_instance, int fd, const char* location, int ka);
void CMockExpectParameters_send_created(CMOCK_send_created_CALL_INSTANCE* cmock_call_instance, int fd, const char* location, int ka)
{
  cmock_call_instance->Expected_fd = fd;
  cmock_call_instance->Expected_location = location;
  cmock_call_instance->Expected_ka = ka;
}

void send_created_CMockIgnore(void)
{
  Mock.send_created_IgnoreBool = (char)1;
}

void send_created_CMockStopIgnore(void)
{
  Mock.send_created_IgnoreBool = (char)0;
}

void send_created_CMockExpect(UNITY_LINE_TYPE cmock_line, int fd, const char* location, int ka)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_created_CALL_INSTANCE));
  CMOCK_send_created_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_created_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_created_CallInstance = CMock_Guts_MemChain(Mock.send_created_CallInstance, cmock_guts_index);
  Mock.send_created_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_send_created(cmock_call_instance, fd, location, ka);
}

void send_created_AddCallback(CMOCK_send_created_CALLBACK Callback)
{
  Mock.send_created_IgnoreBool = (char)0;
  Mock.send_created_CallbackBool = (char)1;
  Mock.send_created_CallbackFunctionPointer = Callback;
}

void send_created_Stub(CMOCK_send_created_CALLBACK Callback)
{
  Mock.send_created_IgnoreBool = (char)0;
  Mock.send_created_CallbackBool = (char)0;
  Mock.send_created_CallbackFunctionPointer = Callback;
}

int make_nonblocking(int sockfd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_make_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_make_nonblocking);
  cmock_call_instance = (CMOCK_make_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.make_nonblocking_CallInstance);
  Mock.make_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.make_nonblocking_CallInstance);
  if (Mock.make_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.make_nonblocking_FinalReturn;
    Mock.make_nonblocking_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.make_nonblocking_CallbackBool &&
      Mock.make_nonblocking_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.make_nonblocking_CallbackFunctionPointer(sockfd, Mock.make_nonblocking_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_make_nonblocking,CMockString_sockfd);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_sockfd, sockfd, cmock_line, CMockStringMismatch);
  }
  if (Mock.make_nonblocking_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_make_nonblocking);
    cmock_call_instance->ReturnVal = Mock.make_nonblocking_CallbackFunctionPointer(sockfd, Mock.make_nonblocking_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_make_nonblocking(CMOCK_make_nonblocking_CALL_INSTANCE* cmock_call_instance, int sockfd);
void CMockExpectParameters_make_nonblocking(CMOCK_make_nonblocking_CALL_INSTANCE* cmock_call_instance, int sockfd)
{
  cmock_call_instance->Expected_sockfd = sockfd;
}

void make_nonblocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_make_nonblocking_CALL_INSTANCE));
  CMOCK_make_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_make_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.make_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.make_nonblocking_CallInstance, cmock_guts_index);
  Mock.make_nonblocking_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.make_nonblocking_IgnoreBool = (char)1;
}

void make_nonblocking_CMockStopIgnore(void)
{
  if(Mock.make_nonblocking_IgnoreBool)
    Mock.make_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.make_nonblocking_CallInstance);
  Mock.make_nonblocking_IgnoreBool = (char)0;
}

void make_nonblocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sockfd, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_make_nonblocking_CALL_INSTANCE));
  CMOCK_make_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_make_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.make_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.make_nonblocking_CallInstance, cmock_guts_index);
  Mock.make_nonblocking_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_make_nonblocking(cmock_call_instance, sockfd);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void make_nonblocking_AddCallback(CMOCK_make_nonblocking_CALLBACK Callback)
{
  Mock.make_nonblocking_IgnoreBool = (char)0;
  Mock.make_nonblocking_CallbackBool = (char)1;
  Mock.make_nonblocking_CallbackFunctionPointer = Callback;
}

void make_nonblocking_Stub(CMOCK_make_nonblocking_CALLBACK Callback)
{
  Mock.make_nonblocking_IgnoreBool = (char)0;
  Mock.make_nonblocking_CallbackBool = (char)0;
  Mock.make_nonblocking_CallbackFunctionPointer = Callback;
}

void setup_signals(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_setup_signals_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_setup_signals);
  cmock_call_instance = (CMOCK_setup_signals_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.setup_signals_CallInstance);
  Mock.setup_signals_CallInstance = CMock_Guts_MemNext(Mock.setup_signals_CallInstance);
  if (Mock.setup_signals_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.setup_signals_CallbackBool &&
      Mock.setup_signals_CallbackFunctionPointer != NULL)
  {
    Mock.setup_signals_CallbackFunctionPointer(Mock.setup_signals_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.setup_signals_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_setup_signals);
    Mock.setup_signals_CallbackFunctionPointer(Mock.setup_signals_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void setup_signals_CMockIgnore(void)
{
  Mock.setup_signals_IgnoreBool = (char)1;
}

void setup_signals_CMockStopIgnore(void)
{
  Mock.setup_signals_IgnoreBool = (char)0;
}

void setup_signals_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_setup_signals_CALL_INSTANCE));
  CMOCK_setup_signals_CALL_INSTANCE* cmock_call_instance = (CMOCK_setup_signals_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.setup_signals_CallInstance = CMock_Guts_MemChain(Mock.setup_signals_CallInstance, cmock_guts_index);
  Mock.setup_signals_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void setup_signals_AddCallback(CMOCK_setup_signals_CALLBACK Callback)
{
  Mock.setup_signals_IgnoreBool = (char)0;
  Mock.setup_signals_CallbackBool = (char)1;
  Mock.setup_signals_CallbackFunctionPointer = Callback;
}

void setup_signals_Stub(CMOCK_setup_signals_CALLBACK Callback)
{
  Mock.setup_signals_IgnoreBool = (char)0;
  Mock.setup_signals_CallbackBool = (char)0;
  Mock.setup_signals_CallbackFunctionPointer = Callback;
}

void check_keepalive_timeouts(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_check_keepalive_timeouts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_check_keepalive_timeouts);
  cmock_call_instance = (CMOCK_check_keepalive_timeouts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.check_keepalive_timeouts_CallInstance);
  Mock.check_keepalive_timeouts_CallInstance = CMock_Guts_MemNext(Mock.check_keepalive_timeouts_CallInstance);
  if (Mock.check_keepalive_timeouts_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.check_keepalive_timeouts_CallbackBool &&
      Mock.check_keepalive_timeouts_CallbackFunctionPointer != NULL)
  {
    Mock.check_keepalive_timeouts_CallbackFunctionPointer(Mock.check_keepalive_timeouts_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.check_keepalive_timeouts_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_check_keepalive_timeouts);
    Mock.check_keepalive_timeouts_CallbackFunctionPointer(Mock.check_keepalive_timeouts_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void check_keepalive_timeouts_CMockIgnore(void)
{
  Mock.check_keepalive_timeouts_IgnoreBool = (char)1;
}

void check_keepalive_timeouts_CMockStopIgnore(void)
{
  Mock.check_keepalive_timeouts_IgnoreBool = (char)0;
}

void check_keepalive_timeouts_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check_keepalive_timeouts_CALL_INSTANCE));
  CMOCK_check_keepalive_timeouts_CALL_INSTANCE* cmock_call_instance = (CMOCK_check_keepalive_timeouts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.check_keepalive_timeouts_CallInstance = CMock_Guts_MemChain(Mock.check_keepalive_timeouts_CallInstance, cmock_guts_index);
  Mock.check_keepalive_timeouts_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void check_keepalive_timeouts_AddCallback(CMOCK_check_keepalive_timeouts_CALLBACK Callback)
{
  Mock.check_keepalive_timeouts_IgnoreBool = (char)0;
  Mock.check_keepalive_timeouts_CallbackBool = (char)1;
  Mock.check_keepalive_timeouts_CallbackFunctionPointer = Callback;
}

void check_keepalive_timeouts_Stub(CMOCK_check_keepalive_timeouts_CALLBACK Callback)
{
  Mock.check_keepalive_timeouts_IgnoreBool = (char)0;
  Mock.check_keepalive_timeouts_CallbackBool = (char)0;
  Mock.check_keepalive_timeouts_CallbackFunctionPointer = Callback;
}

